### ISSUE TITLE
Disable sending TCP options

### ISSUE THREAD

**Issue by hesingh** [esnet/iperf#1031]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the iperf3 mailing list at iperf-dev@googlegroups.com or
question sites such as Stack Overflow
(http://www.stackoverflow.com/).  A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

By default iperf sends any TCP packet with TCP options.  I would like to change the source code to not send any TCP options.  How do I do that?  Later, a knob should be provided to disable sending any TCP options, if a knob doesn't exist already - I don't know.  The same goes for not sending any UDP options.

* Version of iperf3: Latest

* Hardware: x86

* Operating system (and distribution, if any): Linux

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

* Expected Behavior

* Actual Behavior

* Steps to Reproduce

* Possible Solution

_Please submit patches or code changes as a pull request._

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

_If submitting a proposed implementation of an enhancement request,
please use the pull request mechanism._

**Comment by bmah888** [comment]
The question has to do with not sending TCP segments with TCP options.  The presence of TCP options isn't something that iperf3 controls directly, but it's determined by options such as window scaling or the ability of the OS kernel to support features such as SACK (selective acknowledgement).  Basically you would examine the packets from the sending host, decode them to figure out what the TCP options are, and see if there is an easy way to cause those options to not be inserted into each packet.  Some might be possible to do with command-line flags to iperf3, whereas others might require modification of iperf3's source code or kernel settings.

Because the use of TCP options is highly OS-dependent, it's not possible/feasible for iperf3 to have a knob to disable their use.

With respect to UDP, there's no such thing as "UDP options" (at least not in any UDP implementation that I know of).
