### ISSUE TITLE
Iperf does not work properly on UDP when running in Docker

### ISSUE THREAD

**Issue by mostafafarzaneh** [esnet/iperf#1127]
I have run iperf3 on Docker. For TCP it worked fine but when running the client with `-u` option, It cannot connect to the server.

client-side :
> Connecting to host x.x.x.x, port 9000
> iperf3: error - unable to read from stream socket: Connection refused

server-side:
> -----------------------------------------------------------
> Server listening on 9000
> -----------------------------------------------------------
> Accepted connection from x.x.x.x, port 46474

I just publish port 9000 on docker(`-p 9000:9000`). But when running docker with `--net=host`, it works fine.

**Comment by davidBar-On** [comment]
This is **not** an iperf3 issue. The problem is that **port 9000 was published only for TCP** but not for UDP.  By default, the ports specified using docker `EXPOSE` or `-p` are for TCP. To specify ports for UDP, the **`/udp`** should be added.  E.g. `-p 9000:9000/udp`.

This is relevant for the non-host networks, e.g. the default `bridge` network.  With `net=host` the container runs as if it is running in the host network, so all ports are accessible (if not blocked by the OS, etc.).
