### ISSUE TITLE
Jitter overflow

### ISSUE THREAD

**Issue by Ku100vEvgen** [esnet/iperf#1158]
Hi
I use test low speed device ( 10-60kbits/sec )

_iperf3.exe --client speed.as208196.net --port 5201 --udp --interval 10 --time 30  --reverse
Connecting to host speed.as208196.net, port 5201
Reverse mode, remote host speed.as208196.net is sending
[  4] local 172.31.204.208 port 60533 connected to 45.154.168.155 port 5201
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-27.53  sec  8.00 KBytes  2.38 Kbits/sec  101327731611.758 ms  0/1 (0%)
[  4]  27.53-27.53  sec  0.00 Bytes  0.00 bits/sec  101327731611.758 ms  0/0 (0%)
[  4]  27.53-30.00  sec  80.0 KBytes   265 Kbits/sec  53142390297.363 ms  4/14 (29%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-30.00  sec  3.94 MBytes  1.10 Mbits/sec  53142390297.363 ms  4/15 (27%)
[  4] Sent 15 datagrams
iperf Done._

my local iperf
_>iperf3 --version
iperf 3.1.3
CYGWIN_NT-6.1 811ZEV 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64_

**Comment by davidBar-On** [comment]
Seems that this issue was already solved by PR #990.

Note that you are using an old iperf3 version from 2016. There is a site that distributes new iperf3 executable for Windows. This is not an iperf3 official site and I didn't try to use executable from it, but I saw some recomendations about using it.  See [https://files.budman.pw/](https://files.budman.pw/) or [https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/](https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/) (in both download is from the same site).

**Comment by Ku100vEvgen** [comment]
Thanks
I downloaded the program from the link https://iperf.fr/iperf-download.php#windows and did not believe that so old versions
