### ISSUE TITLE
Weird results with speed measured: `iperf3 -s -F file.out `

### ISSUE THREAD

**Issue by romanchyla** [esnet/iperf#1159]
# Context

I was following documentation to establish network speed; memory-memory; disk->memory; disk<-memory and in the last one was getting way too low results. 

It turns out that if I mount the drive over NFS I can achieve higher speeds than what iperf3 reports.

I was curious whether I'm doing something wrong or if this is a potentially a bug with iperf3

* Version of iperf3:

iperf 3.7 (cJSON 1.5.2)
Linux rbox3 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication

* Hardware:

Please see this SF post to see the context/results/measurements:
https://serverfault.com/questions/1065820/very-slow-write-speed-nvme-drive-on-10g-network

# Bug Report

* Expected Behavior

Sending data over 10G with very fast (single) NVME drive on the target machine, I'd expect reported speed to be close to the 10G network connection.

* Actual Behavior

It was 10% - NVME disk can write >1000MB/s; iperf3 memory-memory shows 1GB/s transfers; but the actual write speeds were  ~100MB/s s

* Steps to Reproduce

server: `iperf3 -s -F /tmp/out`
client: `iperf3 -c server -t 30`

**Comment by davidBar-On** [comment]
It seems that a main cause of the problem is the `fsync` done after each write to the file:
https://github.com/esnet/iperf/blob/3b31c4b6ac40481fb6057ed75b8dd6af9c150b34/src/iperf_api.c#L4279-L4280

Using a local built iperf3 on my local computer with SSD disk, the throughput is about 13MB/sec with `fsync` and over 100MB/sec when the `fsync` is removed.

I will submit a PR with a proposed enhancement to make the `fsync()` optional.

**Comment by romanchyla** [comment]
Thank you! I'll try to test it out and update measured results (probably once a new release is available)
