### ISSUE TITLE
Is it possible to connect iperf server with a simple SCTP client?

### ISSUE THREAD

**Issue by asterwyx** [esnet/iperf#1184]

**Comment by asterwyx** [comment]
Hi all,

Does this scenario work? I mean, whether I can communicate with the iperf server using SCTP only or not. Thanks!

**Comment by davidBar-On** [comment]
SCTP should work.  However, for that SCTP should be supported by the OS.  I tried building iperf3 under both Windows WSL Linux and Windows CigWin, and in both cases it seems that SCTP is not supported.

**Comment by bmah888** [comment]
Note that the iperf3 client and server communicate on a TCP control connection before the start of the test, to exchange test parameters (including the protocol, such as SCTP). The SCTP listening socket (on whichever side of the test) doesn't exist before that time. So without doing the TCP control connection, connecting to either the client or server with a separate SCTP client will not work.

**Comment by sanathpholla** [comment]
Hi @bmah888 ,

We have a LoadBalancer sitting in front of client which has a SCTP port open.
When running the iperf3 client with --sctp option, it initially tries to communicate with TCP still, which will fail, because LoadBalancer expects SCTP traffic only and not TCP.
Is there any workaround to try iperf3 in this case?
Should this be submitted as new feature request?

Thanks,
Sanath

**Comment by sanathpholla** [comment]
Okay, thanks for the response @bmah888
