### ISSUE TITLE
Unexpected ip header length

### ISSUE THREAD

**Issue by Zhangyida183** [esnet/iperf#1266]
Using iperf3 to send udp packets. During iperf negotiation, a packet with an abnormal IP header length is generated.
ip header length = 32, but there are 46 bytes(32 bytes data + 14 bytes 0x00)

picture is here [error picture](https://raw.githubusercontent.com/Zhangyida183/Img/master/Error/iperf%20error.png)

# Context

* Version of iperf3: 
iperf 3.5 (cJSON 1.5.2)

* Hardware:
ESXI virtual machine

* Operating system (and distribution, if any):
Linux localhost.localdomain 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication

**Comment by davidBar-On** [comment]
The extra 14 bytes of 0x00 are because of Ethernet packets padding.  The minimum size of Ethernet packet is 64 bytes, including 14 bytes of MAC header and 4 bytes CRC.  Therefore, the IP packet sent over Ethernet should be at least 46 bytes.  Since the IP packet sent is only 32 bytes, 14 padding bytes are required.  See for example [this explanation](http://xyznetwork.blogspot.com/2010/02/why-minimum-ethernet-packet-size-is-64_52.html).
