### ISSUE TITLE
How does IPerf3 UDP works?

### ISSUE THREAD

**Issue by GF-Huang** [esnet/iperf#1331]
Sorry to post a question here that is not a bug. But I'm just very curious why this is happening.

I use IPerf3 as client by: `iperf3.exe -c ping.online.net -p 5207 -u`. I use Wireshark to capture IPerf3 UDP packet. I found that it just send 4 bytes in first UDP packet: `15 cd 5b 07`, then it receive a response packet with 4 bytes: `b1 68 de 3a`. I want to simulate sending the first packet by my program, so I send the same bytes (`15 cd 5b 07`) to **ping.online.net**, but in Wireshark, I see an ICMP Port Unreachable response.

My question is why I send the same bytes to **ping.online.net**, I will get ICMP error, but IPerf3 works well? What happen?

Compare the following images, you will found nothing different in the Data part.

![image](https://user-images.githubusercontent.com/4510984/167035047-8e3d3769-d752-4cf3-bf4a-1df8c3b835d2.png)

![image](https://user-images.githubusercontent.com/4510984/167035134-172007f9-7d10-4a6a-bfe0-1b3aeec300f0.png)

**Comment by davidBar-On** [comment]
> Sorry to post a question here that is not a bug. But I'm just very curious why this is happening.

Just FYI, you could open this a a Discussion, instead of an Issue.

> My question is why I send the same bytes to ping.online.net, I will get ICMP error, but IPerf3 works well? What happen?

iperf3 connection is done using TCP, not UDP, so the TCP 5207 port is open before the client connection (you can verify that using `nc`).  The UDP port is open only during the connecting process, which involves sending cookies and more.

If you want to interface iperf3 server from a your own program, you can probably use [libiperf](https://github.com/esnet/iperf/blob/master/src/libiperf) library (I don't have experience using it, so I cannot help more).

**Comment by GF-Huang** [comment]
Thanks your reply. You're right, after investigation, I found out that it does open a TCP connection first.
