### ISSUE TITLE
Supporting multiple clients

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#140]
_From [skycrawlers2](https://code.google.com/u/111735986419078121651/) on February 18, 2014 02:52:15_

Hi, I just tried to send traffic from two clients.
However, iperf3 showed me a message as below.

iperf3: error - the server is busy running a test. try again later

Many-to-one communication is an important feature I think, so if you have time, please work on it. 
Thanks for your efforts.

_Original issue: http://code.google.com/p/iperf/issues/detail?id=140_

**Comment by mailinglists35** [comment]
Could this be revisited, please?

I need to measure network infrastructure's ability to handle multiple clients to the same server. Workaround is to fire up multiple servers for each client, which is frustrating and time consuming.

Thank you

**Comment by alkisg** [comment]
Hi, on behalf of the https://epoptes.org open source computer lab monitoring tool, where I'm the lead developer, I would like to request this feature as well.
In Epoptes we had implemented a network benchmark tool, based on iperf2.
The server was running this: iperf -s -xS
Many clients were running this in parallel: iperf -c server -r
And then the server was reporting the results in a nice dialog.

This test MUST be run in parallel in order to detect flow control issues, where e.g. a gigabit server sends too much data to a 100 Mbps client, and the switch sends Ethernet pause frames to the server, forcing all communications to 100 Mbps, making the network 10 times slower than it should be.
It CANNOT be detected when the clients are benchmarked separately, one by one.

We've been using this iperf2 feature successfully for many years to detect the flow control and other networking issues.
Now I was trying to update the Epoptes code in order to switch to the newer iperf3 and I realized that it doesn't support it anymore.
We could write our own benchmark function (Epoptes uses python3-twisted), but I would prefer to rely on iperf3, if you decide to implement this feature.

In any case, thank you for iperf2, it's been an excellent tool that helped us a lot in all those years!
(until iperf -r broke in Debian 11's 2.0.14 version, as I reported in sourceforge discussions)

**Comment by davidBar-On** [comment]
Hi @alkisg,  some time ago I submitted PR #1074 for supporting multiple clients by a single server.  The basic idea is that the main server supports the first client by itself, but the second and above clients in parallel are supported by forking (exec) a new server that exits after its client testing completes.

The PR was never tested on a real system, so if you are willing to test whether this solution is working well in your system, I will be happy to support you for issues resolution, required enhancements, etc.

**Comment by alkisg** [comment]
Hello @davidBar-On, thank you very much for the proposal.

Unfortunately if I understood it correctly, that implementation opens a different port for each client, which isn't firewall-friendly, and puts an upper limit (15?) to the number of clients that can connect.

From what I've read so far, epoptes will need to keep using iperf2 2.0.13 (or 2.1.3 when that becomes available in distributions), and later on, it should implement its own benchmarking function using python3-twisted. Maybe even plain sockets could work, like https://github.com/Barthurmun/Iperf-in-Python does.

**Comment by davidBar-On** [comment]
> Unfortunately if I understood it correctly, that implementation opens a different port for each client, which isn't firewall-friendly, and puts an upper limit (15?) to the number of clients that can connect.

Just for the record a block of ports is used, so it can be possible to pe-allocated this block of ports in the firewall.  Also, the 15 clients limit can be changed to any number.  In any case,  continue using ierf2 is probably a safer approach.
