### ISSUE TITLE
iperf3 server crash with --logfile and --json and --rcv-timeout in reverse direction after receiving rcv-timeout bug

### ISSUE THREAD

**Issue by zokl** [esnet/iperf#1469]
Hello,

I found a bug when iperf3 crashed with a segmentation fault on the server site.

iperf3 3.12+ - commit: https://github.com/esnet/iperf/commit/3e57aa2b3b066094697a9b6860180fe234f1a530

It is the same bug that was resolved in PR #1463 but in the reverse direction.

Reproduction of the bug:

```
Server side
iperf3 -J -1 -s -p 6666 -i 1 --rcv-timeout 10000 --snd-timeout 10000 --logfile test.txt

Client side
iperf3 -c XYZ -p 6666 -i 1 -t 300 --rcv-timeout 10000 --snd-timeout 10000 -R

wait few seconds

shutdown interface (mobile, eth etc.)

Wait for iperf3 crash on server side, server crash after rcv-timeout ...
```

**Comment by davidBar-On** [comment]
@zokl, I am unable to recreate the problem, maybe because my environment is different.  My server is running under Widows WSL Ubuntu Linux.  In my test, when I disconnect the network interface from the server's PC, the server properly times out after `snd-timeout`.

Under which OS you are running the server?

Also, in reverse mode the server should time out because it is unable to send for `snd-timeout` time, and not `rcv-timeout`.  Can you set them to different values and verify whether the crash is after `snd-timeout` or `rcv-timeout`?

**Comment by zokl** [comment]
> @zokl, I am unable to recreate the problem, maybe because my environment is different. My server is running under Widows WSL Ubuntu Linux. In my test, when I disconnect the network interface from the server's PC, the server properly times out after `snd-timeout`.
> 
> Under which OS you are running the server?
> 
> Also, in reverse mode the server should time out because it is unable to send for `snd-timeout` time, and not `rcv-timeout`. Can you set them to different values and verify whether the crash is after `snd-timeout` or `rcv-timeout`?

I am so sorry, but my mistake. I have not had my environment in a master state. Everything works. Thank you.
