### ISSUE TITLE
ldconfig needed in make install?

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#153]
@lomaxfrog just ran into a problem on an Ubuntu Linux system where a manual invocation of ldconfig was needed after make install in order for the iperf3 binary to find its shared library.  This was on iperf 3.0.2.

This issue is to investigate what steps we should be doing in this case.  Might be a little tricky because so much of the Makefile stuff is auto-generated.

**Comment by bmah888** [comment]
This really is a generic software installation problem.  We're not going to solve it here, given the difficulties in doing this across multiple platforms.  Closing without a fix.

**Comment by kriswebdev** [comment]
If you want to stick to `/usr/local/lib` instead of `/usr/lib32` on Unbuntu distro, then just run `ldconfig /usr/local/lib` (requires superuser) at the end of `make install`.

See: http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries

**Comment by Chadster766** [comment]
Thanks running ldconfig after "make install" solved the issue for me.

**Comment by nzjc** [comment]
Running Debian 7.8 64Bit (wheezy). Had the issue as prescribed in the title, ran 'sudo ldconfig' post make install, working fine now. Thanks for the help in this thread.

**Comment by tomturner123** [comment]
Had to use this on latest version (3.1.3) with ubuntu. If this is to be a necessary requirement for all ubuntu versions I suggest its worthwhile making it a bit more obvious so that the user wont need to search google / github to get going

**Comment by jangwhan** [comment]
same here with Ubuntu 16.04 (Xenial Xerus). 
I understand this is caused by cross-platform issue(to which I have no clues as to why), but as tomturner123 said, ubuntu better make warning signs about this, unless someone like me get lost again....

**Comment by jmack51** [comment]
Does anyone have a fix for the iperf3 error on Mac OSX?  With 3.2, I'm seeing libiperf.so.0 is not found.

**Comment by bmah888** [comment]
@jmack51:  On mac OS, there won't be a `*.so.0` shared library...mac OS uses a `*.dynlib` extension for its shared libraries.  If "the Python wrapper" refers to iperf3-python, that's a separate project and you probably ought to take this up with them (I'm not sure if there's a bug here or not).

**Comment by bmah888** [comment]
@jmack51:  Ah, disregard, I see where you already opened an issue with thiezn/iperf3-python.

**Comment by jmack51** [comment]
Thanks Bruce, sorry for the spam, for the record that's over in https://github.com/thiezn/iperf3-python/issues/23

**Comment by bmah888** [comment]
I'm going to re-open this issue, even though I don't have a great idea about how to fix it.  There are various use cases:

- Systems that need ldconfig to be run.
- Systems that don't need ldconfig.,
- Systems that need ldconfig with some parameters (e.g. a pathname).
- Systems with no ldconfig (e.g. macOS).
- Cross-compiling.

I'm thinking something like what I proposed on June 10, 2014, but ignoring error conditions.  It'd be great if someone could comment on the cross-compiling case...if you're cross-compiling for some other platform do you do the full `make install` to stage the files somewhere or just `make compile`?

**Comment by BeyondEvil** [comment]
I've run into this issue, and was hoping you could help me figure out a fix.

I'm trying to run iperf3 on my armv5 QNAP NAS.

I managed to install it. But running it, I get this issue: `iperf3: error while loading shared libraries: libiperf.so.0: cannot open shared object file: No such file or directory`

`ldconfig` (w/ or w/o sudo) didn't fix it unfortunately.

`[/] # find . -name libiperf.so.*
./mnt/ext/usr/local/lib/libiperf.so.0
./mnt/ext/usr/local/lib/libiperf.so.0.0.0
./share/HDA_DATA/homes/admin/downloads/iperf-3.5/src/.libs/libiperf.so.0.0.0
./share/HDA_DATA/homes/admin/downloads/iperf-3.5/src/.libs/libiperf.so.0`

`ls -la` from / gives
`lrwxrwxrwx    1 admin    administ        12 Mar 30 10:18 usr -> /mnt/ext/usr/`

`[/usr/local/lib] # ls -la libiperf.s*
lrwxrwxrwx    1 admin    administ        17 Mar 30 21:32 libiperf.so -> libiperf.so.0.0.0*
lrwxrwxrwx    1 admin    administ        17 Mar 30 21:32 libiperf.so.0 -> libiperf.so.0.0.0*
-rwxr-xr-x    1 admin    administ    380032 Mar 30 21:32 libiperf.so.0.0.0*`

I've tried adding `/mnt/ext/usr/local/lib` to `/etc/ld.so.conf` and _then_ running `ldconfig` without luck.

This is what it looked like before (and I have since removed it again):
`[/mnt/ext/usr/local/lib] # cat /etc/ld.so.conf 
/lib
/usr/lib
/usr/local/lib`

**Comment by ralcini** [comment]
@BeyondEvil have you tried to use LD_LIBRARY_PATH environmental variable?

**Comment by BeyondEvil** [comment]
@ralcini No I haven't, (I think). I'll give it a try. 👍

**Comment by rollingslack** [comment]
For the cross compiling query in https://github.com/esnet/iperf/issues/153#issuecomment-365012358, I've used `make install` extensively. I'd guess that most build systems do it as well - particularly if a project is autotool-ized.

**Comment by rollingslack** [comment]
I'd suggest as a first stab at this, the iperf build process could put out messages onto the console suggesting the command that ought to be run. Once we have that, cut over to actually doing it.

Is there a listing of which (*nix)systems need ldconfig to be run, and which don't ? macOS and Windows fall into the list of not requiring ldconfig to be run after make install.

As an aside, I'm curious as to which systems don't need ldconfig to run and how thats managed.

**Comment by bmah888** [comment]
Closing.  This isn't solely an iperf3 problem, and it seems like nobody else has a good solution for it either.  (I would posit that some combination of automake and libtool should be dealing with this issue.)

**Comment by hpjansson** [comment]
Yes, it seems like a libtool issue. The last time I went chasing this, I found the following in the GNU bug tracker:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30402

> In 1997, commit 7f9b4e50 for libtool version 0.6b, the way of running
> ldconfig was changed from running without "-n" to running with "-n".

Based on the discussion there it seems unlikely that this will be reverted, since so much time has passed and the rationale for the change and the risk potential from changing it back seem to be poorly understood. If someone comes across this issue in the future and wants to try for a fix anyway, that's probably as close as you'll get to doing it correctly.
