### ISSUE TITLE
iPerf 3.11 UDP -R option does not work sometimes

### ISSUE THREAD

**Issue by son9701** [esnet/iperf#1563]
hello

I am testing iPerf through my terminal.

If i run iPerf through the command below, it always works in case of TCP, but it doesn't work in case of UDP.

iperf3_11 --client fd01:976a:0:1::fa --time 37 --port 39682 --udp --bandwidth 1524000K -i 1.0 -R --parallel 12

I checked the following response from the server

"unable to read from stream socket: Interrupted system call"

Are there any items to check in this situation?

**Comment by davidBar-On** [comment]
Hi, few questions:
1. What is the the throughput you get when testing using TCP for each of the 12 streams?
2. Does the UDP test run properly if your remove either of both `--parallel` / `--bandwidth` options?
3. If the test is working when `--parallel` is removed, what is the maximum parallel streams that does work?

**Comment by davidBar-On** [comment]
Note that the throughput per TCP stream is about 30Mbits/sec, while in your UDP test you set it to about 1,500Mbits/sec ((for TCP tests the `--bandwidth` has no effect if its value is higher than the network throughput).  Suggest also to try testing UDP with `--bandwidth 30M`.

**Comment by son9701** [comment]
2.
Test on Parallel 12, with this setting on the 8th UDP runs (4th cycle) started having the issue.
When changed the Parallel to 1, the issue showed up on the 16th UDP runs (8th cycle) started having the issue. 

When changed to 0 Bitrate, every UDP calls had the issue. 

3. Since 1. still had the issue I did not check the max parallel.

I will test with UDP with --bandwidth 30M and share the result

**Comment by davidBar-On** [comment]
> When changed to 0 Bitrate, every UDP calls had the issue.

Bitrae 0 means **unlimited** bitrate.  The default is 1Mbps, so either remove the `--bandwidth` option or set `--bandwidth `M`.  Actually this can be combined with the `--bandwidth 30M` test - try different bandwidths.  Suggest to try these tests first with parallel set to 1.

> Test on Parallel 12, with this setting on the 8th UDP runs (4th cycle)

Not sure what you mean by that - test (cycles) was successful 3 times and the 4th test failed?  If this is the case, what do you mean by "8th UDP runs"?

**Comment by son9701** [comment]
I am measuring in an environment that automatically reports iperf messages.
In this environment, tcp and udp are measured once.

Test on Parallel 12
TCP-UDP-TCP-UDP-TCP-UDP-TCP-_UDP_

Test on Parallel 1
TCP-UDP-TCP-UDP-TCP-UDP-TCP-UDP-TCP-UDP-TCP-UDP-TCP-UDP-TCP-_UDP_

The UDP test shown last is causing problems.


Let's check by changing the bitrate of UDP to 30M.

**Comment by son9701** [comment]
Dear david

It does not seem to be a problem when the bitrate of the UDP option is set to 30M.
However, since we are testing in various environments, it may be a problem if the session bit rate exceeds 30M bps.
Is there a way to measure without problems without fixing the bitrate (30M)?

Lastly, I am curious about the cause of the problem when the bitrate is infinite or high in the case of UDP.

**Comment by davidBar-On** [comment]
Hi,
> Lastly, I am curious about the cause of the problem when the bitrate is infinite or high in the case of UDP.

This is because UDP is connection-less oriented protocol, meaning that there is not feedback about whether UDP packets arrived to the server or were lost (this is vs TCP that is connection oriented).  Therefore, if the iperf3 UDP throughput is not limited, it will be limited only by the client's computer resources limitations, mainly the CPU.

If the UDP sending rate is above the network rate, then network buffers in the computer will get filled, causing different issues.  Probably the "unable to read from stream socket: Interrupted system call" error you see is because the network buffers got filled.

> Is there a way to measure without problems without fixing the bitrate (30M)?

Per the explanation above, I am not sure that there is an easy way for not fixing the bitrate.  It may be possible to do that using e.g. shell-script.  When iperf3 runs TCP with unlimited throughput, the actual throughput is about the maximum rate.  Therefore, if TCP test runs first, followed by a UDP test, the reported TCP throughput may be used to set the UDP rate limit (e.g. 80% of the TCP reported rate to be on the safe side).

**Comment by son9701** [comment]
Thank you for your kind explanation
