### ISSUE TITLE
`--reverse` not work well with ` -n`

### ISSUE THREAD

**Issue by nixwl** [esnet/iperf#1637]
- QUESTION：

 I use `-n` to set data size  that  the  Server send to Client, but the Client  as if receiving data from Server continually and over I set  data size

- HOW TO DO：

How can I fix it ？ `-R` can work well with  `-t`  in Server-Client data transmission，I had tested it.

- CODE：

![image](https://github.com/esnet/iperf/assets/80773211/5bc7830a-d551-46c4-a67b-636fdcca21a9)

**Comment by davidBar-On** [comment]
More information about the issue can help:
1. Does iperf3 works o.k. when you use `-n` in **non**-reverse mode?
2. What version of iperf3 your are using for the client and for the server (get the version from `iperf3 -v`)?
3. What is the `$size` you set for the `-n`?  This is important since the default TCP buffer size is 128KB.  Therefore, if for example you set `-n 10K` iperf3 will still send 128KB.  If this is the issue, set `-l` to a value that is not larger than the `-n` value.

**Comment by nixwl** [comment]
Hi, Dear @davidBar-On 

I using `iperf v3.9` in my tests,  this is my test code:

-  client(use -R mode):  `iperf3 -c 127.0.0.1 -p 1234 -B 127.0.0.2 --cport 1235 -f m -i 1 -V -R -n 1M -M 1460`

-  server : `iperf3 -s -B 127.0.0.1 -p 1234 -i 1 ` <br>

I want server send 1M bytes to client, but I don't know why server sent too much data to client ? 

This is the Screenshots：

- server‘s
![image](https://github.com/esnet/iperf/assets/80773211/0346253f-ffac-4af6-98cd-208d6eb3d94e)

- client‘s
![image](https://github.com/esnet/iperf/assets/80773211/a024bcbe-311d-4ea4-ae10-6904e2ffd527)

**Comment by davidBar-On** [comment]
Thanks for the information.  I believe that the issue was fixed by PRs #1054 and #1364, so upgrading to iperf3 version 3.12 or newer should solve the problem.

**Comment by nixwl** [comment]
Very Thanks，after update to Version3.16， this problem sloved
