### ISSUE TITLE
is it necessary to start the client workers after it enter TEST_RUNNING state

### ISSUE THREAD

**Issue by penglei0** [esnet/iperf#1703]
is it necessary to wait until iperf enters the TEST_RUNNING state before starting iperf_client_worker_run to receive data?

The reason I ask this question is because I encountered this test case during testing: 
The last control message of Iperf arrives 4ms later than the data message, causing the receiving socket buffer of that data channel to be overflowed at client side.

in my option, iperf_client_worker_run should be created before it enter "TEST_RUNNING " state; and iperf_client_worker_run thread can be closed If the subsequent state transition times out or fails. This approach does not affect the functionality of iperf, and does not cause the socket buffer to be overflowed.

**Comment by davidBar-On** [comment]
I assume you are referring to test where the server is sending to the client, i.e. reverse or bi-directional.

With current code design there is no major change is the `iperf_client_worker_run` threads will be created after receiving `TEST_START` or `TEST_RUNNING`, because there is message from the client to the server between these two states.  It seems to me that to solve the issue described, additional **"threads creation" state** should be added.  E.g., instead of sending `TEST_RUNNING` the server will:
```
Send `TEST_THREADS_CREATE` -> Create the threads -> Wait for `TEST_THREADS_CREATE` from the client -> Send `TEST_RUNNING`
```
The client will:
```
Wait for `TEST_THREADS_CREATE` -> Create the threads -> Send `TEST_THREADS_CREATE` from the client -> Wait for `TEST_RUNNING`
```

**Comment by penglei0** [comment]
> I assume you are referring to test where the server is sending to the client, i.e. reverse or bi-directional.
> 
> With current code design there is no major change is the `iperf_client_worker_run` threads will be created after receiving `TEST_START` or `TEST_RUNNING`, because there is message from the client to the server between these two states.  It seems to me that to solve the issue described, additional **"threads creation" state** should be added.  E.g., instead of sending `TEST_RUNNING` the server will:
> ```
> Send `TEST_THREADS_CREATE` -> Create the threads -> Wait for `TEST_THREADS_CREATE` from the client -> Send `TEST_RUNNING`
> ```
> The client will:
> ```
> Wait for `TEST_THREADS_CREATE` -> Create the threads -> Send `TEST_THREADS_CREATE` from the client -> Wait for `TEST_RUNNING`
> ```

Agreed. Additional state should be added to ensure the iperf receivers is ready for receiving test data.
