### ISSUE TITLE
Non-monotonic gettimeofday() used for time interval measurements

### ISSUE THREAD

**Issue by nomel** [esnet/iperf#253]
It is not monotonic and changes with things like ntp updates. This can cause strange values. [Here's a good explanation](https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time).

**Comment by bmah888** [comment]
If NTP changes your clock backwards at any time other than a system reboot (when you're not likely to be running iperf3 anyway), then You're Doing it Wrong (tm).

Looking at the manpage for clock_gettime(2), which is what is advocated by the link you provided, it might be better, although I personally have never used it.  Note that it's not portable to all of our primary platforms (in particular, MacOS doesn't support it), so that's a bit of a barrier to adopting it.

**Comment by GabrielGanne** [comment]
Hi,

This got me curious, so I had a look.
The link from @nomel was a very nice explanation (thanks !)

I believe this is also partially covered by https://github.com/esnet/iperf/issues/210

I've written a draft remove gettimeofday calls [here](https://github.com/GabrielGanne/iperf/tree/remove-gettimeofday)
If you're interested, I can clean it up and submit a pull-request.

I think the main issue with it is that it adds a link against librt.
I did not change the logic of the calls, so it's better, but not very conclusive performance wise, as the writing takes pretty much all the time.

```
==> strace.iperf.ref <==
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 96.99    0.016855           0     48753         1 write
  2.15    0.000373           0    195714           gettimeofday
  0.86    0.000150           0     49518           _newselect

==> strace.iperf.test <==
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 98.11    0.018559           0     48026         1 write
  1.24    0.000235           0    192801           clock_gettime
  0.64    0.000122           0     48788           pselect6
```

BR

**Comment by bmah888** [comment]
@GabrielGanne :  Thanks for looking into this!  I haven't forgotten about it, but unfortunately just don't have time to think about it right now...if I don't get back to you in a few weeks can you give me a ping?

**Comment by GabrielGanne** [comment]
@bmah888 
Sure!
Don't worry about it.

**Comment by GabrielGanne** [comment]
Hi,

I hope you had holidays and that they were nice.
This is just a kind reminder about this thread.

Best Regards,

**Comment by bmah888** [comment]
Thanks for the reminder...I need to restore my mental state to look at your patch.

I read through the code and it looks like it'll do what it claims, in other words use `clock_gettime()`.  I'm trying to wrap my mind around how portable this is, or rather how portable can we make it.  Linux and FreeBSD appear to have this system call (not sure at what point they started supporting it).  Very recent macOS (since 10.12) has it also.  While that covers all of the platforms we officially support, I also try to not gratuitously break other platforms.  To do that, it almost feels like we need to some autoconf stuff to detect whether clock_gettime is available and then conditionally either use clock_gettime() or gettimeofday().  That touches a bunch of places in code.

I'm a little skeptical about the actual impact of the problems pointed out in the original bug report.  NTP should only be skewing the clock, and reasonable NTP implementations put limits on how much rate change is allowed to skew the clock.  So while the issue with gettimeofday() are theoretically possible, in practice I think they'll be rare and/or small.

I haven't decided what to do about this patch yet.  We (and I am not sure who "we" is yet) kind of need to determine whether all the code changes are worth fixing a perceived problem that we haven't really seen a lot in existing deployments.

**Comment by GabrielGanne** [comment]
No worries. The issue was interesting to look at, and once the code was here, it seemed right to propose it back to you.
My understanding is that for most modern platforms, there will be no performance improvement at all. Also, you will probably want to discard the 3 new digits `clock_gettime` could give you.

Anyway, take your time, and should this pop up again in the future for some reason, do not hesitate to ask me to have a run at it again.

Best regards

**Comment by pesiwang** [comment]
use c++11 chrono::steady_lock please!
