### ISSUE TITLE
Window size affects UDP perfromance

### ISSUE THREAD

**Issue by abdel-alasfar** [esnet/iperf#261]
I'm monitoring the performance between two Alix 3d2 devices with OpenWRT barrier breaker installed on both of them and they are connected wirelessly. IPERF-3.0.11 is installed on both firmwares.

The results that I get (after many trials) without specifying the -w parameter are different from those after specifying that parameter (for UDP traffic), even though it should be ignored in case of UDP traffic is generated.

I noticed that the throughput was higher and unreliable (went beyond the specified rate within some seconds) while the packet loss percentage was very high (about 35%), after specifying the window size.

The command which was executed on the client:
iperf3 -c <IP ADDRESS> -t 30 -u -b 35M [-w 512K]

The command which was executed on the server:
Iperf3 -s

Below are the screen shots of the results:

This screen shot was taken without specifying the window size for UDP
![client-u](https://cloud.githubusercontent.com/assets/9304530/7135074/76d9314e-e2a3-11e4-968e-df2ad6806f7e.png)

This screen shot was taken after specifying the window size (-w 512K)
![client-w](https://cloud.githubusercontent.com/assets/9304530/7135090/aa923cce-e2a3-11e4-929a-9aec8739bc46.png)

**Comment by bmah888** [comment]
We (@bltierney and myself) have seen interesting behavior in this area as well.  What really happens when you specify the ```-w``` option is that you're setting the socket buffer size on the sending side (maybe the receiving side too, I don't remember).  This directly affects the TCP socket buffer size, which is what you'd expect.  But the socket buffer size is also applicable to UDP sockets.  What we observed was that if we set extremely large buffers, we can improve UDP throughput for very large (multi-Gbps) UDP flows.

So iperf3 is doing what it's supposed to do (I guess we could have named the option a little better), although the effect for UDP is a little unclear.

Closing this issue.
