### ISSUE TITLE
iperf --bind has no effect

### ISSUE THREAD

**Issue by MPW1412** [esnet/iperf#263]
Hello,

situation: Laptop connected to a local network via lan and wlan at the same time. I want to test the wlan speed againt a local computer.

So I run:

```iperf3 --bind <ip-of-wlan-interface> -c <destination>```

Result is ~917 Mbit/s. The results shows that obviously the lan connection and not the wlan connection was used.

```$ iperf3 --version
iperf 3.0.7
Linux <removed> 3.18.0-031800rc5-generic #201411162035 SMP Mon Nov 17 01:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```

Thanks for reading
MPW

/edit: Just tested against most recent git version, bug is still in the latest git version:

````$ ./iperf3 -version
iperf 3-CURRENT
Linux <removed> 3.18.0-031800rc5-generic #201411162035 SMP Mon Nov 17 01:36:34 UTC 2014 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy````

**Comment by bmah888** [comment]
You have two interfaces onto the same IP subnet?  I'm not sure if the Linux IP stack will do what you want in this case.  You might need to implement some sort of policy routing to make sure packets go out the right interface.

Alternatively, set it up so that the client can access the server over separate subnets for the wireless and wired networks.

I don't think this problem is unique to iperf3.

**Comment by MPW1412** [comment]
Hm, Welle I guess beeing connected to the same network via Lan and wlan is not so uncommon these days.

I thought there might be a way, to force iperf to use one interface, but if the kernel cant handle that, I need to find another way.

Thanks for your reply.
