### ISSUE TITLE
Potential Infinite Loop or Crash by spurious pointer in Switch statement 

### ISSUE THREAD

**Issue by jtobiasciq** [esnet/iperf#271]
In csjon.c, line 256, a while loop does a post increment on a pointer (i.e."ptr2++"), then switch(*ptr2) before checking the value.  This could be any value, without a check, and the default case: statement could either fall through and allow the loop to continue, or create an ACCESS FAULT and crash.

**Comment by bmah888** [comment]
I'm not seeing this.  The file is ```cjson.c``` right?  I see the post-increment and the switch statements, but they are in difference clauses of an if...then...else statement so they won't both be executed on the same iteration of the loop.  Can you clarify?

**Comment by jtobiasciq** [comment]
Yes, as the switch statement has a default case at the end, which an errant value will very likely hit, it will be execute and the while loop continues (maybe):

 1.  if spurious but somehow a valid access, it could loop again, and potentially forever (relatively, it hits end of valid region)
 2.  If not valid, an ERRBADACCESS violation will cause a crash.

Sincerely,
Jay Tobias
CARRIER iQ – Mobile Service Intelligence
www.carrieriq.com

**Comment by bmah888** [comment]
Hrm.  I've read this code through again, and I'm still not finding a problem, or rather, I acknowledge that the problems you pointed out could happen, but there are many ways to encounter these even without the use of the backslash escape character processing.

It's indeed true that there are only a discrete set of characters that are valid after a backslash character, according to http://www.json.org/.  Those are the characters handled in the switch statement, plus '/' and '\' and '"', each of which expand to themselves.  I'm not sure what the "correct" behavior is in the case of other characters following an escape character.

Both of the two errors you pointed out are essentially walking off the end of the string into an invalid memory region.  This can happen anyway in the case of a corrupted string; I suppose a string with a backslash at the end of the string could also cause this problem.  Note that since a JSON string requires a double-quote at the start and end of the string, this latter case is also malformed.

I don't think this is a critical problem, although it's indeed true that the escape processing in the loop could have some better error handling.

I wonder if the upstream cjson.c code has a better way to handle this?  I haven't checked.

**Comment by jtobiasciq** [comment]
I agree it's not going to crash or loop infinitely every time it enters the loop, but by post incrementing ptr2, if could end up with a point value, that when dereferenced is either accessible but spurious, or errant and invalid.  In the former case you get infinite loop, and in the second a crash of BAD_ACCESS or invalid.

As rare as this might be, I would not could this way; instead just add one line to ensure that the case never occurs.  It may not seem critical now, but if it ever causes a bug, this kind of pointer dropping through the valid cases of the switch statement to the "default:" where it increments and try again is just not as robust and could prove difficult to find.  

Just sharing my experience.  If you don't think it's worth bullet proofing, that's up to you.
Cheers :)

**Comment by bmah888** [comment]
I'm looking at this issue with respect to the newer version(s) of cjson.c imported since the issue was first filed; note in particular that a newer version of cjson.c was imported as a result of a memory handling fault reported by a third party about 9 months ago.  I believe (but admittedly haven't rigorously proven) that with the checks near the start of parse_string() that this code is safe.

I'm going to close this issue as "wontfix" for now, it can be reopened if need be.
