### ISSUE TITLE
jitter buffer length?

### ISSUE THREAD

**Issue by ajohnson23** [esnet/iperf#297]
If I run the following:
iperf3 -V -c somehost -l 1200 -R -u -b 5m -t 360 -w 1M -p 54004

I'll get back packet loss stats like:
[  4]  60.00-61.00  sec   595 KBytes  4.88 Mbits/sec  0.091 ms  13/521 (2.5%)  
[  4]  61.00-62.00  sec   594 KBytes  4.87 Mbits/sec  0.111 ms  14/521 (2.7%)  
[  4]  62.00-63.00  sec   593 KBytes  4.86 Mbits/sec  0.091 ms  14/520 (2.7%)  
[  4]  63.00-64.00  sec   593 KBytes  4.86 Mbits/sec  0.094 ms  15/521 (2.9%)  

Given this is UDP, I assume iperf3 considers any packet not received after x amount of time to be a lost packet. How do I control this x value?
This is useful for WAN tests where you want to know whether packets are being lost or just delayed due to congestion. This is sometimes called "jitter buffer length" but goes by different names, I'm sure...

**Comment by bmah888** [comment]
If I remember right, we're using the sequence numbers to detect loss...there isn't a timeout mechanism involved.  This means that it can be a little difficult to tell the difference between lost and reordered packets.  (If there are no reordered packets then the sequence-number-based approach works better than a timeout-based approach, because there's no timeout that needs to be tuned.)
