### ISSUE TITLE
source code mix of tabs and space

### ISSUE THREAD

**Issue by teto** [esnet/iperf#300]
While debugging some problem, I noticed that the code indentation is a mix of space tabs.
This breaks display in any decent editor and makes contribution harder, which convention to choose ?

**Comment by bmah888** [comment]
This is unfortunately due to a number of different people working on the sources over time.  As with many open source projects, it's probably best to try to follow the prevailing conventions of the code around where you are working.  A couple of people have proposed re-indenting the entire source tree but I think that's actually a bad idea because that gratuitiously touches many lines in the tree and makes searching the history hard.

As for me when I do new code, I generally use the BSD indentation, 4-space indents, 8-space tabs.

**Comment by teto** [comment]
I would vote for a cleanup. There are indeed some tolerance in some
projects for instance on trailing spaces or for instance in wireshark where
one file fully uses spaces and another one on tabs but iperf3 is different,
you have files with an alternance of tabs/spaces every 2/3 lines, some
using 2 spaces tabs, some 8 spaces tabs and ends up making it hard to
follow the code and also to contribute since new contributors are likely to
fix this on top of their patch, making patch reviewing harder.

As for the history, git can ignore whitespace changes and as a cleanup
doesn't move lines, it should be quite ok.


2015-09-18 19:35 GMT+02:00 Bruce A. Mah <notifications@github.com>:
