### ISSUE TITLE
iperf3 3.0.11 wrong UDP Jitter summary number 

### ISSUE THREAD

**Issue by gpgeorgiev** [esnet/iperf#303]
I am running a simple udp test using iperf3 version 3.0.11
I was trying to calculate the same summary statistics but using per second numbers and then noticed that the Jitter Summary number is not equal to the average of the per second Jitter numbers. Something more, the Summary Jitter is equal to the value reported in last second.

Is this a know bug or have somebody else monitored similar peculiarities?

**Comment by sambonator** [comment]
I too noticed the summary jitter number always equal the last second reported jitter.  
Additionally, jitter numbers do not look right, since as you lower the bandwidth with -b, the jitter always rises.  This appears to be a bug in the jitter algorithm... or perhaps I'm just not understanding the way in which iPerf3 performs the udp test and jitter calculations...

**Comment by bmah888** [comment]
Is this related in some way to #204?

**Comment by bltierney** [comment]
I'm getting the same value for jitter with iperf-2.0.9 and iperf-3.1.6, so perhaps this is no longer an issue?

Also, the code to compute jitter appears to be the same in iperf2 and iperf3.

Can you confirm if you still have this problem?

**Comment by bmah888** [comment]
No response to previous question, so closing.  Please re-open if you think this problem still exists.
