### ISSUE TITLE
some questions about transfers the iperf3 gives:

### ISSUE THREAD

**Issue by imagecmos** [esnet/iperf#306]
[ ID] Interval               Transfer        Bandwidth       Retr
[ 15] 0.00-10.00sec  9.45 GBytes  8114 Mbits/sec   0      sender
[ 15] 0.00-10.00 sec 9.43 GBytes  8103 Mbits/sec           receiver
iperf Done.

1.Why the transfers are different at sender line and receiver line?what does that means?
2.In my tests, the interval at receiver computer always larger the sender computer? I don't understand this

pleas help me,thank you!

**Comment by bmah888** [comment]
These are due to differences in timing between the sender and receiver processes, and possibly the effect of network performance.  It looks to me like the sender writes out 9.45 GBytes on its data connection, then immediately follows this with a message that says (essentially) "stop testing now" on its control connection to the receiver.  If the receiver receives the control connection message before it's received all of the data, it'll ignore any remaining data on the data connection.

There can also be some differences in timing between the sender and receiver that might cause them to measure time intervals slightly differently.
