### ISSUE TITLE
Trying to Compile in Alpine

### ISSUE THREAD

**Issue by antoniomch** [esnet/iperf#328]
I'm trying to compile in Alpine 3.2.3 x86_64, but getting some errors:

Configure output: http://pastebin.com/Y0Q6zqtJ
make: http://pastebin.com/LGkfxfp2
make install: http://pastebin.com/kYcay7zK

config.log: http://pastebin.com/uckziqvt

Any help ?

**Comment by bmah888** [comment]
Note:  This is iperf 3.0.10.

The build process can't find struct tcp_info, which the configure system assumes is available because this is a Linux platform.  This file is a part of the kernel headers and/or sources, so you could try installing those (not sure how to do that on Alpine Linux, I'm more of a FreeBSD guy myself).

Alternatively, iperf 3.1 detects platform-specific features in a different way, and *might* be a little more dependable in this situation, rather than assuming the existence of tcp_info from the fact it's a Linux platform.  So you could try the newer version of iperf3.

**Comment by pjebs** [comment]
@antoniomch  did you manage to get it to build on alpine linux?
