### ISSUE TITLE
Trouble running multiple iPerf3 instances

### ISSUE THREAD

**Issue by filhoweuler** [esnet/iperf#362]
I'm running a prototype of a platform that will monitor the quality of the network of a ISP here in Brazil. We currently have arround 30 probes that has a software able to connect with a iPerf3 server and execute some tests. We are running one iPerf3 instance on a different port for each hardware on the server side. The server has a 1Gbit link to be able to execute the tests.

The tests are running fine when executed separatedly on each probe and we get the expected results. The trouble happens when all the probes execute tests at the same time, each one in a different iPerf3 instance running on the server. Links of 20Mbits are getting 4~5Mbits so I'm wondering if is there some limitation on running multiple iPerf3 instances.

Have you ever used iPerf3 on this scenario? Are there any known issues related? 

Thanks in advance!

**Comment by bmah888** [comment]
The main use case for iperf3 doesn't involve running multiple tests at a time (in fact we use some scheduling software to serialize tests so that no more than one is running a time).  It's possible that there's some bottleneck in your server, but host issues can be a little tricky to deal with.  We regularly get tens of gigabits per second in single-stream tests, so there shouldn't be any intrinsic limit in iperf3 itself.

**Comment by janmaris** [comment]
Hi, while not the main use case to run multiple iperf3 processes, what is the actual issue doing so? My customer needs to test bandwidth and QoS settings, so I need to run multiple iPerf3 servers on different tcp/udp ports. I cannot really run each process on another server. 
I could consider linux containers, but I would first try to understand what the actual issue is. 
I'm actually launching multiple processes and this seems to work, apart from the fact that I need to start each process manually.
If I copy & paste the list of processes into the shell, or I use a similar startup script I get an output after the second or third process that is launched (as a daemon of course):

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

all processes are launched with the "-D" flag.

Thanks.
Jan
