### ISSUE TITLE
iperf3: error - unable to connect to server: Invalid argument

### ISSUE THREAD

**Issue by johnnyah** [esnet/iperf#406]
Can't get iperf3 to connect over ipv6: e.g.:

ON HOST:
## Server listening on 5201

ON CLIENT:

bash-4.3# iperf3 -6 -c fe80::2a0:f4ff:fe0c:221 -p 5201
iperf3: error - unable to connect to server: Invalid argument

ping6 works:

bash-4.3# ping6 -I eth2.4005 fe80::2a0:f4ff:fe0c:221
PING fe80::2a0:f4ff:fe0c:221(fe80::2a0:f4ff:fe0c:221) from fe80::2f0:a4ff:fe0c:43f eth2.4005: 56 data bytes
64 bytes from fe80::2a0:f4ff:fe0c:221: icmp_seq=1 ttl=64 time=59.3 ms
64 bytes from fe80::2a0:f4ff:fe0c:221: icmp_seq=2 ttl=64 time=0.209 ms
64 bytes from fe80::2a0:f4ff:fe0c:221: icmp_seq=3 ttl=64 time=0.229 ms

Running embedded linux on a powerpc build:

bash-4.3# uname -a
Linux 10.13.51.53 2.6.34.13 #16 PREEMPT Wed Apr 27 09:28:54 PDT 2016 ppc GNU/Linux

Has anyone seen this before, thx, Johnny

**Comment by bmah888** [comment]
My guess is that this is broken because you're trying to connect over a link-local address.  The argument to the `-c` command-line flag doesn't have a link scope specification, so the IP stack doesn't know to which link the link-local address applies.  (In contrast, in your `ping6` command example, the link was specified with the `-I eth2.4005` flag.

I'm not sure how well this would work, but try specifying the server as `-c fe80::2a0:f4ff:fe0c:221%eth2.4005`.  Or you could use an IPv6 globally routable address, or an FQDN.

**Comment by bmah888** [comment]
Closing...I'm pretty sure now that the answer given was correct.

**Comment by ashishzankar** [comment]
iperf and iperf v3 are not compatible.
