### ISSUE TITLE
Incorrect omitting on Windows XP

### ISSUE THREAD

**Issue by LordVeider** [esnet/iperf#428]
Iperf 3 client normally working with omit (-O) option on Windows 7, 8, 10. but wtf on Windows XP?
![omitw8](https://cloud.githubusercontent.com/assets/2705211/15648749/14fa86f8-2686-11e6-87cb-dbdcbafe30f9.png)
![omitwxp](https://cloud.githubusercontent.com/assets/2705211/15648750/14facdac-2686-11e6-9922-83f41f173528.png)

**Comment by bmah888** [comment]
Is this related to #443?

If you still think this is an issue, can you describe what's the expected behavior, and what which OS is on the top and which is on the bottom?

Note also that Windows XP is not an officially supported platform for iperf3 (on a side note it's also EOL-ed by Microsoft, shouldn't have any systems running XP!).
