### ISSUE TITLE
Compilation fails on Solaris 10 Sparc - Iperf 3.1.3

### ISSUE THREAD

**Issue by jhfecchio** [esnet/iperf#454]
# /usr/sfw/bin/gmake

(...)
Making all in src
gmake[1]: Entering directory `/srv/source/iperf-3.1.3/src'
/usr/sfw/bin/gmake  all-am
gmake[2]: Entering directory`/srv/source/iperf-3.1.3/src'
/bin/bash ../libtool  --tag=CC   --mode=link cc -g -g -g -R/srv//source/iperf-3.1.3/src/.libs/ -L/srv/source/iperf-3.1.3/src/.libs/ -o iperf3 iperf3-main.o libiperf.la -lsctp -lnsl -lsocket -lresolv -lrt -lm 
libtool: link: cc -g -g -g -o .libs/iperf3 iperf3-main.o  -L/srv/source/iperf-3.1.3/src/.libs/ ./.libs/libiperf.so -lsctp -lnsl -lsocket -lresolv -lrt -lm -R/usr/local/lib -R/srv//source/iperf-3.1.3/src/.libs/
Undefined                       first referenced
 symbol                             in file
htonll                              ./.libs/libiperf.so
ntohll                              ./.libs/libiperf.so
ld: fatal: symbol referencing errors. No output written to .libs/iperf3
gmake[2]: **\* [iperf3] Error 1
gmake[2]: Leaving directory `/srv/source/iperf-3.1.3/src'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory`/srv/source/iperf-3.1.3/src'
gmake: **\* [all-recursive] Error 1

**Comment by nike38rus** [comment]
I'm experiencing the same issue. I couldn't compile any of 3.x release on my system.
Please tell if you need more info and I'll give it

**Comment by bmah888** [comment]
Sigh, it looks like Solaris 10 doesn't have htonll(3) or ntohll(3), but newer Solaris and OpenSolaris (I think) do.  My Solaris-fu is pretty old and I'm not familiar with all the different Solaris versions and variants.

I'm not sure what to do for you on this, the best I can think of would be to modify the case that handles Solaris in `src/portable_endian.h` to also check the version of Solaris to be sure it's new enough.  In theory, then any older Solaris should fall through to the "unsupported" default case.

**Comment by nike38rus** [comment]
Well, Solaris 10 is still supported by Oracle. Are you going to drop support of Solaris 10?

**Comment by bmah888** [comment]
Solaris 10 was never a supported platform to begin with.  Linux, FreeBSD, and macOS are the supported platforms.

Clearly iperf3 works on other platforms, and we'll try not to break them going forward, but ESnet has never committed to supporting anything other than the three above.  That's particularly true for platforms we don't even have in-house, such as Solaris 10.

We'd be happy to adopt a tested patch for a minor code change that fixes Solaris 10 support, doesn't break anything else, and is submitted as a code request.  That's why there's a "Help Wanted" label on this issue.  Any takers out there?

**Comment by nike38rus** [comment]
Oh, I understand. Unfortunately, I don't have any competencies to help to solve this issue...
