### ISSUE TITLE
iperf3 UDP test functionality depends on SO_REUSEADDR implementation

### ISSUE THREAD

**Issue by belaz9** [esnet/iperf#472]
Hi,
It looks like UDP functionality in part of "connection" management breaks when code is ported to platforms with generic BSD socket API support like ExpressLogic NetX. iperf_udp_accept() is trying to netannounce() the new socket that is attempted to bound to already open UDP port. On NetX platform SO_REUSEADDR socket option is not working the same way for UDP as Linux/Windows implementations, and bind fails. Some research (http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t/14388707#14388707 and http://hacked10bits.blogspot.com/2014/12/udp-binding-and-port-reuse-in-linux.html) shows that later BSD implementations have SO_REUSEPORT option that represent desired behavior, however this option is not available on most platforms.
I wonder if a more portable solution would be not to reuse port numbers for UDP test.
Thanks.

**Comment by bmah888** [comment]
After very briefly reading the stackoverflow posting (hard to do because it has a lot to say), I'm wondering if the right thing is to do `SO_REUSEPORT` if it's available and `SO_REUSEADDR` if not.  That having been said I've put all of about 30 seconds worth of thought into this, so I'm not even sure if that preserves the desired behavior on our main target platforms (Linux, FreeBSD, macOS).

**Comment by rossro** [comment]
This seems that SO_REUSEADDR doesn't work well on Cygwin as well. This is probably the reason that multiple UDP streams don't work on Cygwin: https://github.com/esnet/iperf/issues/489
I've created a branch that uses different port for each UDP stream and it seems to be working well on Cygwin: https://github.com/rossro/iperf.git
The different ports are controlled by the server. When the server accepts a UDP stream, it send a new port number to the client (instead of sending arbitrary value of 987654321). The client uses this port number for the next UDP stream. If the client receives invalid port value (e.g. 987654321) it keeps using the initial port number.  This gives some backward compatibility to the the client as it can work with older servers.

**Comment by bmah888** [comment]
Closing this for now, we can re-open this if someone else wants to work on it.
