### ISSUE TITLE
iperf 3.1.2 can output invalid JSON

### ISSUE THREAD

**Issue by TheRealDJ** [esnet/iperf#520]
When IPERF outputs data in exponential notation, it does so incorrectly.

Should be XeY (X times 10 to the Y)
Actual output: Xe Y (invalid space after 'e')

So JSON becomes something like:
{"socket":7,"start":0,"end":15.0119,"seconds":15.0119,"bytes":11116296,"bits_per_second":5.924e 06,"omitted":false}

Run this through json_reformat (tells you exactly where the problem is):
echo '{"socket":7,"start":0,"end":15.0119,"seconds":15.0119,"bytes":11116296,"bits_per_second":5.924e 06,"omitted":false}' | json_reformat 
lexical error: malformed number, a digit is required after the exponent.
          16296,"bits_per_second":5.924e 06,"omitted":false} 
                     (right here) ------^

My JSON decoder is written in perl ... A simple regex can be used as a work-around:
$json =~ s/(\d+)e (\d+)/$1e$2/g;

Thanks.
DJ

**Comment by bmah888** [comment]
That definitely looks like a problem.  On my macOS Sierra system and iperf-3.1.7 (or whatever release it was I rolled a few days ago) I get JSON output that looks like this:
```
			"streams":	[{
					"socket":	6,
					"start":	0,
					"end":	1.000030,
					"seconds":	1.000030,
					"bytes":	4818568736,
					"bits_per_second":	3.854739e+10,
					"omitted":	false
				}],
```
That `3.854739e+10` is legal JSON but I had to look that up in the spec.

Er, waitaminute.  That was iperf-3.1.2?  We did a couple of updates to the embedded copy of the cjson library since then.  Can you retest with something more current?  In particular 3.1.3 or later?  If you still get this problem on a more current version of code, please send me some more platform details.

**Comment by TheRealDJ** [comment]
I have added a line to my code to log any of these errors. I am still running 3.1.3 on the client and server. I will update one of my servers that is currently showing errors to 3.1.7 and see if the errors stop.

**Comment by bmah888** [comment]
Sounds good, thanks.

**Comment by bmah888** [comment]
I'd like to close this issue.  If you see this problem with newer code, feel free to reopen this issue.  Thanks!
