### ISSUE TITLE
iperf3 delay, loss and jitter

### ISSUE THREAD

**Issue by desta161921** [esnet/iperf#532]
Is possible to add delay, loss and jitter in addition to measuring bandwidth using iperf3 for TCP and UDP packets?

**Comment by bmah888** [comment]
Not all of these measurements are visible to iperf3 depending on what protocol is used.  For example for TCP, user-land applications don't (typically) get to know anything about packet loss because TCP guarantees lossless, in-order delivery.

For UDP, iperf3 exposes packet loss and jitter.

Because these are one-way transfers, computing delay (particularly with unsynchronized clocks) is difficult.  Two-way round-trip delays can be computed using the ping(8) program.  For a program that measures one-way delays, try owamp(8).
