### ISSUE TITLE
iperf3 latency measurement and time resolution

### ISSUE THREAD

**Issue by JodieChuang** [esnet/iperf#547]
Dear iperf developers and maintaners,

I have three questions about measuring with iperf3.

* Is iperf3 able to measure the latency of a network? Since iperf3 is able to measure jitter, which is the latecy variation, I think iperf3 should be able to measure the latency.
* What's the time resolution for jitter and latency? I see that, using UDP, jitter is accurate to microseconds, e.g., 1.846ms. So, is microsecond the highest time resolution of iperf3? I expect the resolution would be higher.
* Does iperf3 synchronize the time of the two networking ends before measuring jitter? Due to different time domains, a fine time synchronization should be needed. I wonder how iperf3 gaurantees the reliability of the jitter measurement.

If any docs about these questions, please let me know. Thank you very much.

Best,
huan

**Comment by bmah888** [comment]
iperf3 is primarily a bandwidth tester, not a latency tester.  There are other utilities that can do this, such as ping or owamp.

The time resolution depends quite a bit on the underlying hardware and operating system.

iperf3 doesn't do time synchronization.  iperf3 tests don't require any particular time synchronization between the client and server, an upcoming authentication feature will require synchronization on the order of seconds.

We'd like to keep the use of the issue tracker on GitHub for actual issues or contributions to the software, not for basic Q&A.  Thanks.

**Comment by scotia70** [comment]
@JodieChuang You can measure jitter without knowing the latency.

If I tell you before a test that I will send two packets, the second packet one millisecond after the first, and you receive the second packet 2 milliseconds after the first, then the jitter is 1ms (a network with zero jitter would have the second packet arrive 1ms after the first).

Latency is far more difficult to measure than jitter unless the receiver is the same tester as the sender (because there is only one clock counting time).  With different testers you need to ensure their clocks are synchronised somehow.  A lot of latency measurements are simply the round-trip time divided by 2 (which is easy as the receiver is the same tester as the sender).

Jitter is easy as it's the variation in latency of subsequent packets, or inter-packet delay variation.

**Comment by AndrewSav** [comment]
@bmah888 
> We'd like to keep the use of the issue tracker on GitHub for actual issues or contributions to the software, not for basic Q&A.

What would you like use for basic Q&A?
