### ISSUE TITLE
problem with summary report when sending from code in 'master' to iperf3.1.7

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#574]
./iperf3 -c hostname -p5400 -u -b1M

gives this:

[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  6]   0.00-5.00   sec   611 KBytes  1.00 Mbits/sec  0.000 ms  0/455 (0%)  sender
[  6]   0.00-0.00   sec   611 KBytes   **nan (null)s**/sec  0.351 ms  0/455 (0%)  receiver

**Comment by bmah888** [comment]
This is somewhere between a regression and a backward compatibility bug.

What's happening is that as a part of the 3.2 reporting fixes, we need the server to send over its ending timestamp.  3.1 and earlier don't do that.  The fix is (will be) for the client to fall back to using its own ending timestamp for computing the server-side statistics if the server doesn't supply that timestamp.  This is of course inaccurate but it's exactly what 3.1 and earlier do.  Testing this fix now...

**Comment by bmah888** [comment]
After the above fix, we see something like this on the client side summary:
```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms  0/906 (0%)  sender
[  4]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.065 ms  0/906 (0%)  receiver
```
It might not be accurate to have the same timestamps on the sender and receiver, but it's what older iperf3 did.  It's better than having NaN values, and in any case it's the best we can do with the information we have.
