### ISSUE TITLE
Iperf3 - sender window vs outstanding bytes

### ISSUE THREAD

**Issue by desta161921** [esnet/iperf#579]
Why does the iperf3 client (sender) receives more outstanding bytes than the sender window when we dump the traffic at the sender side? Theoretically, it shouldn't receive outstanding bytes larger than the sender window. Here are the iperf3 commands i am using

Client command
`iperf3 -c 10.0.0.1 -b 300m -p 5201-t 10 -i 1  `

Server command

`iperf3 -s`

**Comment by bmah888** [comment]
For future reference we'd like to not use the iperf3 issue tracker for user questions.  Please either use the mailing lists or a question site like Stack Overflow.

If I understand your question correctly, the answer is probably because iperf3's user-level pacing operates on the level of TCP user payloads.  If you're counting bytes from a packet dump, you're also seeing the TCP and IP headers, probably Ethernet protocol headers as well.
