### ISSUE TITLE
Consider changing 'Bandwidth' to 'Bitrate' in iperf3 output

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#583]
The term 'bandwidth' is really incorrect.

should we change:
[ ID] Interval           Transfer     Bandwidth       Retr

to
[ ID] Interval           Transfer     Throughput       Retr

This does make the '-b' flag a bit confusing tho, and we dont want to change that.

Thoughts anyone?

**Comment by bmah888** [comment]
Isn't the basically the same as #516?

Few thoughts:

I don't have an issue changing the human-readable output, but we're the faced with the question of whether or not to rename the JSON "bandwidth" field(s), remembering that there are programs that consume the JSON.  I think that's why we closed #516.  (Like do we change the JSON "schema" or let the human output and JSON output use different phraseology?)  I'm up for revisiting that.

As far as `-b` goes, "bitrate" has (in my mind anyway) the same connotation as "throughput" but it also starts with the same letter as "bandwidth", so maybe we could use that term, at least when describing the command-line option.

**Comment by bltierney** [comment]
Ah, I forgot about #516. I pulled this as a separate request out of one of the other issues.

But we cant change the JSON. That would break too many things. So maybe we just leave it alone. At least the man page using the right terminology.

Lets think about this a bit more.

**Comment by bmah888** [comment]
Rough idea:  Maybe we can change the human-facing phraseology including documentation, leave the JSON schema as-is, and also make `--bandwidth` into `--bitrate` or something like that but maintain backward compatibility?  I think that's as far as we can push this idea without breaking stuff.  I am not to what extent something might parse the human-readable output and might break if we were to change that (hopefully nothing).

**Comment by bmah888** [comment]
Addendumb:  I'm stupid.  There's no issue in the JSON, we write it as `bits_per_second`, which is kind of clunky but at least accurate.  There's no `bandwidth` in the JSON at all:
```
Bruce-Mahs-MacBook-Pro:iperf% src/iperf3 --client localhost --json | grep bandwidth
Bruce-Mahs-MacBook-Pro:iperf%
```

**Comment by bmah888** [comment]
All done, at least to the point that it makes sense to do.  The places I didn't touch (deliberately) are variable names in code (probably not worth the effort) and member names in JSON structures (can't change these without breaking compatibility).  Closing.
