### ISSUE TITLE
OUT OF ORDER during UDP testing

### ISSUE THREAD

**Issue by fl1212** [esnet/iperf#605]
Iperf 3.1.6
Win10 TH2

I am running iperf to generate packets between my host PC to a VM and I receive some strange results sometimes. This is not consistent.
Command: iperf3.exe -c 10.10.10.2 -t 60 -O 1 -fm  -V  -u  -b 1000m  -R  -l 5000.

Results:
iperf3: OUT OF ORDER - incoming packet = 1498599 and received packet = 1531366 AND SP = 4
iperf3: OUT OF ORDER - incoming packet = 1498647 and received packet = 1531414 AND SP = 4
iperf3: OUT OF ORDER - incoming packet = 1498656 and received packet = 1531423 AND SP = 4
iperf3: OUT OF ORDER - incoming packet = 1498672 and received packet = 1531439 AND SP = 4
iperf3: OUT OF ORDER - incoming packet = 1498688 and received packet = 1531455 AND SP = 4
[  4]  59.00-60.00  sec   112 MBytes   937 Mbits/sec  0.039 ms  2741/24956 (11%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-60.00  sec  7.03 GBytes  **1006 Mbits/sec**  276.766 ms  177259/1511665 (12%)  
[  4] Sent 1511665 datagrams
[SUM]  0.0-60.0 sec  39595 datagrams received out-of-order
CPU Utilization: local/receiver 27.3% (8.9%u/18.4%s), remote/sender 39.8% (1.0%u/38.8%s)

**Comment by DennisEdlund** [comment]
I think the issue is in packet size -l 5000.
If you don't have large packetsize configurated on you switcher you might only be able to have -l 1472 without fragmentation.

**Comment by bmah888** [comment]
@fl1212:  This issue tracker is for filing bug reports, enhancements, and pull requests for iperf3.  It's not a forum for user support questions.  Could you post your questions to the iperf-users list? Thanks!

(The messages you see are admittedly slightly confusing, but they indicate that the iperf3 server received some UDP packets out of order.  The numbers indicate the expected and actual packet sequence numbers seen.  As @DennisEdlund commented, fragmentation might play a role in this.  In any case you are probably seeing suboptimal results by sending such large UDP datagrams unless you're on a jumbo frame capable network.)

I'm leaving issue #604 open because your question reveals an actual, minor improvement we can make in iperf3's behavior.

**Comment by fl1212** [comment]
I understand, I thought it can be an issue as I can see the problem every few runs and with or without the -l option. 
Thank you.
