### ISSUE TITLE
Multithread iperf3 utilizes 100% CPU 

### ISSUE THREAD

**Issue by Davidm01** [esnet/iperf#606]
Hi,

I've been using Iperf3 3.1.2 on a machine with 16 cores running Linux.
I have noticed that during 3 iperf3 client test runs on single machine towards 3 different iperf3 server hosted machines, the iperf3 client utilizes 100% CPU and it makes the client to run for very large time even though we provide less test time interval(-t).  At times it  results in connection timeout.
And to make a note the iperf3 client that we using are -P,-O,-t,-J,-p. (Even tried with CPU affinity)
Am I missing something? Any thoughts why it may behave this way?

Thanks,
David

**Comment by bmah888** [comment]
This issue tracker is for posting bug reports, enhancement requests, and pull requests for iperf3.  User questions and requests for help should go to the iperf-users list.

Do note that iperf3 is a single-threaded process, mostly because it was designed to test single-stream performance.  If doing multiple parallel streams is a part of your use case, you could consider trying a recent build of iperf2, which is multi-threaded.  Version 2.0.8 or newer would be best, as it contains a number of important bug fixes.

**Comment by pprindeville** [comment]
How much work is porting the threading to iperf3?

**Comment by bmah888** [comment]
I'd say multithreading would need a major code reorganization.  It's not just a simple feature that can just be dropped into place, unfortunately.
