### ISSUE TITLE
iperf3 client IPv6 not working with -B flag

### ISSUE THREAD

**Issue by rpandav** [esnet/iperf#618]
* Version of iperf3: iperf 3.1.6

* Hardware: 2 NIC Cards
```
eno1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 192.168.252.85  netmask 255.255.255.0  broadcast 192.168.252.255
        inet6 fe80::ea39:35ff:fe38:ac7c  prefixlen 64  scopeid 0x20<link>
        ether e8:39:35:38:ac:7c  txqueuelen 1000  (Ethernet)
        RX packets 26803614  bytes 3385170808 (3.1 GiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 6684998  bytes 4191425115 (3.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xfe500000-fe520000

enp5s0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 192.168.252.121  netmask 255.255.255.0  broadcast 192.168.252.255
        inet6 fe80::6eb5:fb0:b193:37cc  prefixlen 64  scopeid 0x20<link>
        ether f0:7d:68:b8:c0:fb  txqueuelen 1000  (Ethernet)
        RX packets 23640238  bytes 3486805611 (3.2 GiB)
        RX errors 0  dropped 331574  overruns 0  frame 0
        TX packets 1010814  bytes 53615350 (51.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

* Operating system (and distribution, if any): Linux visiontest 3.10.0-514.21.1.el7.x86_64

# Bug Report

I am trying to run iperf for IPv6 but I want to client to bind to an IPv6 address. However, it results in an invalid argument error.

```
[root]# iperf3 -6 -c fe80::6eb5:fb0:b193:37cc%enp5s0 -B fe80::ea39:35ff:fe38:ac7c -p 8801
iperf3: error - unable to connect to server: Invalid argument
[root]# iperf3 -6 -c fe80::6eb5:fb0:b193:37cc%enp5s0 -B fe80::ea39:35ff:fe38:ac7c%eno1 -p 8801
iperf3: error - unable to connect to server: Invalid argument
```

When I don't specify the bind parameter for the client, it works correctly.

```
[root]# iperf3 -6 -c fe80::6eb5:fb0:b193:37cc%enp5s0 -p 8801
Connecting to host fe80::6eb5:fb0:b193:37cc%enp5s0, port 8801
[  4] local fe80::6eb5:fb0:b193:37cc port 50538 connected to fe80::6eb5:fb0:b193:37cc port 8801
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  4.35 GBytes  37.3 Gbits/sec    0   3.31 MBytes
[  4]   1.00-2.00   sec  4.39 GBytes  37.7 Gbits/sec    0   3.31 MBytes
[  4]   2.00-3.00   sec  4.54 GBytes  39.0 Gbits/sec    0   3.31 MBytes
[  4]   3.00-4.00   sec  4.45 GBytes  38.2 Gbits/sec    0   3.50 MBytes
[  4]   4.00-5.00   sec  4.18 GBytes  35.9 Gbits/sec    0   3.50 MBytes
[  4]   5.00-6.00   sec  4.35 GBytes  37.4 Gbits/sec    0   3.50 MBytes
[  4]   6.00-7.00   sec  4.45 GBytes  38.2 Gbits/sec    0   3.50 MBytes
[  4]   7.00-8.00   sec  4.43 GBytes  38.1 Gbits/sec    0   3.50 MBytes
[  4]   8.00-9.00   sec  4.27 GBytes  36.7 Gbits/sec    0   3.50 MBytes
[  4]   9.00-10.00  sec  4.28 GBytes  36.7 Gbits/sec    0   3.50 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  43.7 GBytes  37.5 Gbits/sec    0             sender
[  4]   0.00-10.00  sec  43.7 GBytes  37.5 Gbits/sec                  receiver
```

Can someone shed some light?

PS: Do I have to explicitly specif the ethernet interface after the IPv6 address followed by a %? I read an issue about it being a link local address. Would it be necessary if the IPv6 is a global address?

Thanks in advance

**Comment by bmah888** [comment]
When you specify an IPv6 link-local address, you always need to include an interface, because that defines the scope where the link-local address is valid.  This isn't necessary (or valid if I remember correctly) for the case of IPv6 global addresses.

Note that in the second sample command-line you gave (thanks for giving such complete information by the way) you specified different interfaces for the `-c` and `-B` arguments.  This isn't going work because it means that the IPv6 packets would have link-local source and destination addresses with different interface scopes.  I'm not sure if that was a typo on your part, or if you're trying to express something other than what my mental model is.  Note that the client's `-c` argument needs to have the interface scope expressed as an interface name on the client host, not the server host.

**Comment by rpandav** [comment]
Thanks for the quick reply. 

My intention is to drive packets from one ethernet interface eno1 (source) to the other enp5s0 (destination). When I try to do this using IPv4, I don't see any problems.

```
[root]# iperf3 -c 192.168.252.121 -B 192.168.252.85 -p 8801
Connecting to host 192.168.252.121, port 8801
[  4] local 192.168.252.85 port 12225 connected to 192.168.252.121 port 8801
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  4.66 GBytes  40.0 Gbits/sec    0   1.31 MBytes
[  4]   1.00-2.00   sec  4.90 GBytes  42.1 Gbits/sec    0   1.31 MBytes
[  4]   2.00-3.00   sec  4.50 GBytes  38.7 Gbits/sec    0   1.44 MBytes
[  4]   3.00-4.00   sec  4.32 GBytes  37.1 Gbits/sec    0   1.44 MBytes
[  4]   4.00-5.00   sec  4.32 GBytes  37.1 Gbits/sec    0   1.44 MBytes
[  4]   5.00-6.00   sec  4.32 GBytes  37.1 Gbits/sec    0   1.44 MBytes
[  4]   6.00-7.00   sec  4.33 GBytes  37.2 Gbits/sec    0   1.44 MBytes
[  4]   7.00-8.00   sec  4.33 GBytes  37.2 Gbits/sec    0   1.44 MBytes
[  4]   8.00-9.00   sec  4.33 GBytes  37.2 Gbits/sec    0   1.44 MBytes
[  4]   9.00-10.00  sec  4.34 GBytes  37.3 Gbits/sec    0   1.44 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  44.4 GBytes  38.1 Gbits/sec    0             sender
[  4]   0.00-10.00  sec  44.3 GBytes  38.1 Gbits/sec                  receiver

iperf Done.
```

So for it to work for IPv6, do I try to make the IPv6 address for the interfaces global IPs (and not link local)? So that a router connected to these devices is able to identify which interface it needs to route the packets to?

In the case for IPv6 when I didnt specify the binding interface, where do the packets originate from?

**Comment by bmah888** [comment]
I admit I'm having a little difficulty understanding what you're trying to accomplish but here's what I think I understand and why it's not doing what you want:

I think you have a host with two NICs (eno1 and enp5s0) attached back-to-back or to the same switch.  They're both assigned IP addresses in the same subnet.  You want traffic to go out one interface and back in through another.  (I don't get the use case for this.)

In your IPv4 example in your previous comment, what's happening is that the packets aren't even leaving the host.  The Linux IP stack sees the outbound packet and, noticing that the destination address matches one of the interfaces assigned to the host, loops it around in software.  It never touches the wire.  I tried this with one of our multi-homed test hosts, starting up an iperf3 server bound to one interface address and having a client bound to the other interface address.  There is no physical connection between the NICs, but I managed to get 51Gbps through the software loopback.  So your IPv4 example isn't really doing what you want (look at the measured bitrate, is a 38.1Gbps transfer consistent with the hardware you have?).

To do something what you want with IPv6 link-local addresses, you probably want something like:
```
# iperf3 --server --bind fe80::6eb5:fb0:b193:37cc%enp5s0 --port 8801

# iperf3 --client --bind fe80::ea39:35ff:fe38:ac7c%eno1 --client fe80::6eb5:fb0:b193:37cc%eno1 --port 8801
```
Look carefully at the `--client` argument.  It's got the IPv6 link-local address of the enp5s0 addresses but we're forcing the packets to go out eno1.

If you use IPv6 global addresses, I think it's likely you'll get similar results to what you got with IPv4 (bogus results due to software loopback).  I haven't tried this though.  If you don't specify the binding address, the packets go out the interface that's specified in the routing table.  (If the other end of the connection is on the same subnet it's just the interface going to that subnet.  Otherwise it's the interface going to the next-hop gateway as defined in the routing table.)

At this point I'm pretty convinced there's no iperf3 bug involved...closing this issue.  If you'd like to continue this conversation, it should happen on the iperf-users or iperf3-dev mailing lists, not the issue tracker.  Thanks.
