### ISSUE TITLE
Jitter statistic detalization

### ISSUE THREAD

**Issue by Confucij** [esnet/iperf#630]
Hi,
I'm wondering is it possible to enhance jitter statistic? To be more specific: add maximum, minimum and jitter distribution?

**Comment by bmah888** [comment]
I'm going to assume that you're asking about the UDP tests.  There isn't, really a way to compute a maximum and minimum one-way delay, mostly because we don't have synchronized clocks between the sender and receiver.  We can compute the jitter because we use an algorithm actually doesn't require synchronized clocks or a round-trip of data (see comments around line 148 of `src/iperf_udp.c`, also RFC 1889).

ping(8) does a pretty good job of computing two-way delay statistics.  Within the context of perfSONAR, we use owamp to measure one-way delays...perhaps that might be a better tool for what you're interested in.
