### ISSUE TITLE
Regression in 3.1/3.2: iperf server fails after ~15 seconds with "Bad file descriptor"

### ISSUE THREAD

**Issue by iamfionn** [esnet/iperf#645]
* Version of iperf3: 3.2, 3.2rc1 and latest commit on master (cd5d89d36d8b863f2e412e63d4f1d0adec3bda0e).

* Hardware: MBP (Arch Linux, 2015), MBP (MacOS, 2017), VPS (Arch Linux).

* Operating system (and distribution, if any): Arch Linux, MacOS.

### Bug Report

* Expected behaviour: setting `-t 0`, I expect iperf to run indefinitely.

* Actual behaviour: the connection is dropped after about 15 seconds.

* Steps to reproduce: run iperf 3.2 as a server with `iperf3 -s` and a client (any version) with `iperf3 -c $HOST -t 0` (can be entirely local, with `HOST=localhost`); after ~15 seconds, the client will report
```
iperf3: error - control socket has closed unexpectedly
```
and the server will report
```
iperf3: error - select failed: Bad file descriptor
```
(this can also be reproduced in reverse mode).

**Comment by bmah888** [comment]
This is a weird problem on a couple levels.  I see it on the tip of the master and 3.1-STABLE branches, but not the tip of 3.0-STABLE (tested variously on macOS Sierra and CentOS 7).  The test shouldn't stop like that, so there's definitely a bug there.

I'm not sure what the correct behavior is, on the other hand.  Your "run indefinitely" makes some sense, but on the other hand it'd also make sense to not allow this case at all, so that a client can't conduct a DoS attack against a server (a counter-argument is that a server should be able to specify a maximum test length).

I'm going to dig a little more into this and try to understand what's going on.  So far I have the following interesting result:

Server (iperf-master), client (iperf-master):  Failure
Server (iperf-3.0-stable), client (iperf-master):  OK
Server (iperf-master), client (iperf-3.0-stable):  Failure
Server (iperf-3.0-stable), client (iperf-3.0-stable):  OK

This so far implies that there's a problem on the server side with newer iperf.

BTW thanks for a well-formulated bug report!

**Comment by bmah888** [comment]
What's happening here is that if `-t 0` is set on the client, that value isn't passed to the server (which then assumes the default duration of 10 seconds).  The server sets a sort of watchdog timer for 5 seconds past the total test length (which is the value of `-t` and `-i`), so that's where the 15 seconds comes from.  The solution seems to be to pass the value of `-t` to the server unconditionally, but I'm digging around to see if this makes some other problem.

The behavior for setting a timer on the server side was added in PR #446, although it didn't really create the bug we're seeing here.

**Comment by iamfionn** [comment]
I just tried issue-645 (2e51e486d4d4b1958f75d2e2d37b860bcf431734); it obviously works perfectly. Thanks for explaining why this happens.

I don't see this as a DoS threat, since clients can send `-t 86400`, or repeatedly make connections. As you said, it seems like it should be up to the server to allow or disallow these connections. I suspect that with authentication this matters even less.

**Comment by bmah888** [comment]
@iamfionn:  Thanks for the testing!
