### ISSUE TITLE
Error messages not output on stderr

### ISSUE THREAD

**Issue by cygnus2048** [esnet/iperf#688]
Some Iperf errors are not being output on stderr, but incorrectly on stdout.
Example, when the server is terminated during a test:
     iperf3: error - unable to write to stream socket: Connection reset by peer

* Version of iperf3:
latest
* Hardware:

* Operating system (and distribution, if any):
Ubuntu

* Expected Behavior
Errors should be output to stderr
* Actual Behavior
Errors are output on stdout
* Steps to Reproduce
Kill server during a test
* Possible Solution
```
--- iperf_error.c.orig	2018-01-16 14:11:37.223097393 -0500
+++ iperf_error.c	2018-01-16 14:11:50.007310125 -0500
@@ -45,7 +45,7 @@
     if (test != NULL && test->json_output && test->json_top != NULL)
 	cJSON_AddStringToObject(test->json_top, "error", str);
     else
-	if (test && test->outfile) {
+	if (test && test->outfile && test->outfile != stdout) {
 	    fprintf(test->outfile, "iperf3: %s\n", str);
 	}
 	else {
@@ -67,7 +67,7 @@
 	cJSON_AddStringToObject(test->json_top, "error", str);
 	iperf_json_finish(test);
     } else
-	if (test && test->outfile) {
+	if (test && test->outfile && test->outfile != stdout) {
 	    fprintf(test->outfile, "iperf3: %s\n", str);
 	}
 	else {
```

**Comment by bmah888** [comment]
As I see it, the idea is that if we're sending output to a file (not stdout), then put error messages to that file.  Otherwise (and this includes cases where we print to stdout or where the test structure and/or output file pointer are invalid) print to stderr.  I think this makes sense but I'm going to ask someone else to look at this too.

I wonder if the existing (admittedly odd) behavior was introduced when I originally added the `--logfile` option.

**Comment by bmah888** [comment]
Here's a test case for this change.  Before:
```
bmah-centos7:iperf% src/iperf3 --client fubar > /dev/null 
bmah-centos7:iperf% 
```
After:
```
bmah-freebsd11:iperf% src/iperf3 --client fubar > /dev/null 
iperf3: error - unable to connect to server: 
bmah-freebsd11:iperf% 
```
In an unrelated note:  We do not anticipate any effect on the perfSONAR use case because it expects JSON format output, which is unaffected by this code change.
