### ISSUE TITLE
Bitrate calculation standard

### ISSUE THREAD

**Issue by kaushikthedeveloper** [esnet/iperf#714]
Hello.

Have turned to writing up an issue out of exhaustion. Have been searching to get the standard followed for the calculation of `bitrate` (throghput) in iperf3. So far have not been able to find anything conclusive, with proof that it is the method being followed here. Could someone pls give a short version of the standard being followed in this respect?

@bmah888 : sorry to disturb. But could you pls look into this whenever time permits?

**Comment by bmah888** [comment]
It's the number of payload bytes divided by the time.  Both quantities can be different between the sending side and the receiving side.  Note specifically that iperf3 doesn't take into account protocol overheads such as the TCP/IP headers, encapsulation headers/trailers, etc.

In the future it might be better to post questions like this to the iperf-users list rather than using the issue tracker.  Closing.

**Comment by kaushikthedeveloper** [comment]
Thank you for taking the time to answer that. Will make it a point to post future questions in the mailing list.

And very interesting detail about the protocol overhead not being taken into consideration. Will have to look into that.
