### ISSUE TITLE
Jitter starts at unreasonably high values (e.g. 1e5)

### ISSUE THREAD

**Issue by stephane-caron** [esnet/iperf#842]
# Context

* Version of iperf3: 3.6+

* Hardware: Intel PCs

* Operating system (and distribution, if any): Ubuntu 10.04 (server) and 14.04 (client)

# Bug Report

* Expected Behavior: Jitter estimate on server side starts at reasonable values

* Actual Behavior: Jitter starts at high values, e.g. 410264.464 ms. The lower the bandwidth, the higher the initial Jitter value seems to be, and the slowest it converges to an actual (plausible) value. Here is an example of server output:

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Time: Thu, 24 Jan 2019 17:07:29 GMT
Accepted connection from 10.4.5.111, port 36450
      Cookie: ouvbe4cot2ahpyyq6jbjm74seqb5gixr4jvc
      Target Bitrate: 500000
[  5] local 10.4.5.1 port 5201 connected to 10.4.5.111 port 45865
Starting Test: protocol: UDP, 1 streams, 1448 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  59.4 KBytes   485 Kbits/sec  29101.499 ms  0/42 (0%)  
[  5]   1.00-2.00   sec  60.8 KBytes   498 Kbits/sec  1815.991 ms  0/43 (0%)  
[  5]   2.00-3.00   sec  62.2 KBytes   510 Kbits/sec  107.945 ms  0/44 (0%)  
[  5]   3.00-4.00   sec  60.8 KBytes   499 Kbits/sec  8.846 ms  0/43 (0%)  
[  5]   4.00-5.00   sec  60.8 KBytes   498 Kbits/sec  2.497 ms  0/43 (0%)  
[  5]   5.00-6.00   sec  60.8 KBytes   498 Kbits/sec  1.957 ms  0/43 (0%)  
[  5]   6.00-7.00   sec  60.8 KBytes   498 Kbits/sec  1.979 ms  0/43 (0%)  
[  5]   7.00-8.00   sec  60.8 KBytes   498 Kbits/sec  1.911 ms  0/43 (0%)  
[  5]   8.00-9.00   sec  62.2 KBytes   510 Kbits/sec  1.953 ms  0/44 (0%)  
[  5]   9.00-10.01  sec  60.8 KBytes   496 Kbits/sec  1.960 ms  0/43 (0%)  
[  5]  10.01-10.04  sec  1.41 KBytes   385 Kbits/sec  1.961 ms  0/1 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5] (sender statistics not available)
[  5]   0.00-10.04  sec   611 KBytes   499 Kbits/sec  1.961 ms  0/432 (0%)  receiver
```

* Steps to Reproduce: the client (Ubuntu 14.04) runs
```bash
$ iperf3 -c SERVER_IP -u -t 10 -V -b 500k
```
while the server (Ubuntu 10.04) runs
```bash
$ iperf3 -s -V
```
To illustrate the relationship with `b`, here is another sample server output when the client increases `-b 1m`:

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Time: Thu, 24 Jan 2019 17:10:54 GMT
Accepted connection from 10.4.5.111, port 36484
      Cookie: sodpmmnhudog6gizoir5pbrknl3npz2vbqlh
      Target Bitrate: 1000000
[  5] local 10.4.5.1 port 5201 connected to 10.4.5.111 port 46875
Starting Test: protocol: UDP, 1 streams, 1448 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   120 KBytes   980 Kbits/sec  1815.781 ms  0/85 (0%)  
[  5]   1.00-2.00   sec   122 KBytes   997 Kbits/sec  8.829 ms  0/86 (0%)  
[  5]   2.00-3.00   sec   122 KBytes   997 Kbits/sec  1.997 ms  0/86 (0%)  
[  5]   3.00-4.00   sec   122 KBytes   997 Kbits/sec  2.027 ms  0/86 (0%)  
[  5]   4.00-5.00   sec   123 KBytes  1.01 Mbits/sec  1.870 ms  0/87 (0%)  
[  5]   5.00-6.00   sec   122 KBytes   997 Kbits/sec  1.837 ms  0/86 (0%)  
[  5]   6.00-7.00   sec   122 KBytes   997 Kbits/sec  1.722 ms  0/86 (0%)  
[  5]   7.00-8.00   sec   123 KBytes  1.01 Mbits/sec  1.859 ms  0/87 (0%)  
[  5]   8.00-9.00   sec   122 KBytes   997 Kbits/sec  1.788 ms  0/86 (0%)  
[  5]   9.00-10.00  sec   122 KBytes   997 Kbits/sec  1.791 ms  0/86 (0%)  
[  5]  10.00-10.03  sec  4.24 KBytes  1.16 Mbits/sec  1.684 ms  0/3 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5] (sender statistics not available)
[  5]   0.00-10.03  sec  1.19 MBytes   998 Kbits/sec  1.684 ms  0/864 (0%)  receiver
```

**Comment by wetglass** [comment]
Sync NTP on the client and server, that'll fix it! A quick-and-dirty fix is `sudo ntpdate`, assuming ntp is already present and there's network connectivity to a clock source.

There's other perf testing tools that complain about NTP being out of sync when executed. Wouldn't hurt (much) to warn about unsync'd ntp mucking jitter values. There really isn't any documentation on iperf jitter beyond googling some threaded q's. Going off topic, seems iperf server only reports the final jitter value in the bottom line summary.

**Comment by bmah888** [comment]
Well actually not...the jitter algorithm doesn't depend on synchronized clocks between the client and server.  It uses the deltas in timestamps between packets as taken on the source and on the destination to compute jitter.

(That said, having synchronized clocks is good for many other reasons, and I consider it a given for pretty much any well-run UNIX system with network connectivity.)

**Comment by wetglass** [comment]
@bmah888 I'd been having the same issue as @stephane-caron for some time. Thus I'd eventually concluded, successfully, that if NTP wasn't sync'd, jitter values wouldn't be stable.

Example steps to reproduce:
VM on Win10, laptop goes to sleep, wakes up later (say next day), NTP is not running on the VM, so the time offset could be several thousand seconds. Iperf from the VM as a client to a remote host, and jitter starts really high (5-digits) then proceeds to normalize over the next ~5-20 seconds, though the normalization values do not appear accurate. Sync'ing NTP will then produce expected jitter values upon execution of iperf.

Based on your explanation @bmah888 , it sounds like in the scenario above, no normalization should occur and jitter values, be it high or normal, should remain constant. Either way, sync'ing NTP is the right way to go.

**Comment by bmah888** [comment]
Is this still a problem?  It seems like it's worth investigating, although I don't recall seeing this on my test systems.

**Comment by davidBar-On** [comment]
There seem to be a <b>minor bug in `iperf_udp_recv()`</b> that causes the issue.  The bug is that the first packet received, `sp->jitter` is set to about the time difference between the server and client machines time regardless of the jitter.  The solution is that <b>when the first packet is received, `sp->jitter` should not be changed</b>.  Something like (changes in <b>bold</b>):

<pre><code><b>static in first_time = 1;</b>
....
sp->prev_transit = transit;
<b>if (first_packet)
    first_packet = 0;
else</b>
    sp->jitter += (d - sp->jitter) / 16.0;
</code></pre>

Explanation of the jitter values shown in the first test case from <b>@stephane-caron</b>:
Assume that there is <b>no jitter</b>.  The first packet sets `sp->jitter` to the time difference between the client and server machines.  Each of the following packets received will reduce the jitter by a factor of _15/16_ (this also explains why jitter convergence is slower with lower throughput).
Therefore, the about 43 packets received in an interval will reduce the jitter by <b>(15/16)^43=0.0623</b>.  E.g. the _29101ms_ in the first interval are expected to be reduced to about _29101*0.0623=1813ms_ which is about the actual _1816ms_.
Making the calculation backward from the _29101ms_, based on the 41 packets received after the first packet gives: _29101*(1/((15/16)^41))=410285ms_ which is about _7 minutes_.  Therefore it seems that the high jitter seen is because of the above bug and because there are about 7 minutes difference between the server and client machines.

**Comment by bmah888** [comment]
@davidBar-On : Interesting analysis on this problem, thank you.  I'm going to have to stare at that for a bit.  Thanks also for your comments on various other iperf3 issues...I'm hoping to get caught up later this week.

**Comment by bmah888** [comment]
OK I've been able to reproduce the problem and I understand what's going on now.  Basically the problem is that `sp->prev_transit` (supposed to be the time difference between packet sending as seen at the sender and packet reception as seen at the receiver) is initialized to be zero.  However if typical values for this variable are significantly different from zero (either because of a large one-way delay or clock skew or both), this can result in a very high initial jitter.  The solution I implemented (pull request coming up) is to explicitly initialize `sp->prev_transit` on the first packet.  Thanks to @davidBar-On for pointing this out (and @wetglass for bringing up the clock skew problem).
