### ISSUE TITLE
using strerror for errors from getaddrinfo()

### ISSUE THREAD

**Issue by Safari77** [esnet/iperf#846]
# Context

* Version of iperf3:
git

* Hardware:
Ryzen

* Operating system (and distribution, if any):
Fedora 28, x86_64

# Bug Report

* Expected Behavior
Proper errors to user when connecting to a server fails

* Actual Behavior
```
$ iperf3 -c net
iperf3: error - unable to connect to server: No such file or directory
$ iperf3 -c net -4
iperf3: error - unable to connect to server: 
$ iperf3 -c net -6
iperf3: error - unable to connect to server: No such file or directory
```

* Steps to Reproduce

* Possible Solution
```      
GETADDRINFO(3)       Linux Programmer's Manual            GETADDRINFO(3)
...
getaddrinfo() returns 0 if it succeeds, or one of the following nonzero error codes:
...
       EAI_SYSTEM
              Other system error, check errno for details.
```
```errno``` is valid only when ```EAI_SYSTEM``` is returned.
In other cases user should see "temporary error", "host not found (nxdomain)", or "no IPv4/IPv6 addresses found", or some system error (then you can use strerror).

_Please submit patches or code changes as a pull request._

**Comment by bmah888** [comment]
For every call to `getaddrinfo()` we need to save the return value (instead of just checking it). We need to stash that return value somewhere that `iperf_strerror()` can get to it.  Then define new error codes that are variants of existing ones (i.e. `IESTREAMCONNECTGAI` for `IESTREAMCONNECT`), which have similar iperf3 error messages, but set say a local variable `gerr` so that we'll know to check the return code, and then append the result of `gai_strerror()` or `strerror(errno)` as appropriate.
