### ISSUE TITLE
Server enables tcp congestion control even when not specified

### ISSUE THREAD

**Issue by MauricioRoman** [esnet/iperf#852]
The following brackets imply that the server will proceed to enable TCP congestion control even when this option is not specified.

https://github.com/esnet/iperf/blob/40e7c05440583f229edd6b6ca05c5d97b66fcf15/src/iperf_server_api.c#L507-L508

They should be removed.

**Comment by bmah888** [comment]
No, not really.  The code below line 508 retrieves the congestion control algorithm in use, regardless of whether the option to choose a different algorithm was set or not (note the use of `getsockopt()` rather than `setsockopt()`).

Note that TCP always has a congestion control algorithm, the option being discussed just picks which one to use.
