### ISSUE TITLE
Bind to all interfaces by default for UDP tests

### ISSUE THREAD

**Issue by mfeit-internet2** [esnet/iperf#860]
This began in https://github.com/perfsonar/pscheduler/issues/819:

# Context

* Version of iperf3:  3.6, behavior is still present in code on master branch.

* Hardware:  x86, but probably everything.

* Operating system (and distribution, if any):  Linux, CentOS 7

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):  None.

# Bug Report

* Expected Behavior:  UDP tests bind to all interfaces on the host when acting as the server without the `-B` switch in effect.

* Actual Behavior:  UDP tests bind to the first-found interface (see #505).

* Steps to Reproduce:  Run any UDP test on a system with multiple interfaces.

* Possible Solution:  If the `-B` switch isn't in effect, bind the UDP socket to `IPADDR_ANY`.

**Comment by bmah888** [comment]
After considerable testing, we're not able to reproduce the bug originally reported in #505.  Either it was an idiosyncracy of the environment in which the problem was encountered, or it was unintentionally fixed as a consequence of some other change.  The way we addressed this in #505 was a documentation change...I am going to partially revert that change to reflect reality as I see it.
