### ISSUE TITLE
Priority and individual transfer time per packet

### ISSUE THREAD

**Issue by CC-vga** [esnet/iperf#886]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the iperf3 mailing list at iperf-dev@google-groups.com or
question sites such as Stack Overflow
(http://www.stackoverflow.com/).  A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3:
3.1.*
* Hardware:
x86_64
* Operating system (and distribution, if any):
Windows10
_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

* Expected Behavior

* Actual Behavior

* Steps to Reproduce

* Possible Solution

_Please submit patches or code changes as a pull request._

# Enhancement Request

* Current behavior

* Desired behavior
Hi, 

Thank you for your time on developing an opensource network tester! I would like to use IPerf also due to its well documented functionality. I do hope that the following are implemented functionalities, but looking into the documentation I couldn’t find:
-	How to set the priority of an UDP stream?
-	How to record on server side the transfer time for individual packets? 

All best
Voica

* Implementation notes

_If submitting a proposed implementation of an enhancement request,
please use the pull request mechanism._

**Comment by bmah888** [comment]
Please be aware that iperf-3.1 is quite frankly, ancient.  Many improvements, features, and bug fixes have been added since then.  The current version of iperf3 is 3.6, with 3.7 planned soon-ish.  In addition, we do not officlally support iperf3 on any Windows platform, although other parties have compiled it and made binaries available.

The priority of packets is sometimes expressed using the TOS/DSCP bits in the IPv4 and IPv6 headers.  Those can be set using the `--tos` or `--dscp` command-line parameters. This will require support in the hosts and routers involved.

iperf3 is not capable of computing the one-way latency directly. This requires synchronized clocks (which is not a requirement for running iperf3), as well as additional measurement and computation that iperf3 does not perform.  You might be better off using some tool such as OWAMP to do delay measurements (even ping, which records two-way delays, might be useful).

**Comment by CC-vga** [comment]
Thanks for the priority tip!
