### ISSUE TITLE
Iperf3 packet loss is so large and -w option

### ISSUE THREAD

**Issue by sky20041129** [esnet/iperf#897]
Server:Ubuntu 18.04  -> iperf3 -s 
Client:Ubuntu 18.04 -> iperf3 -u -c IP -b 10000M -t -i 5 -w 256k

1.I peer 10G ethernet card to peer  10G ethernet card in PC and IPC.
When I use default mtu (1500), the packetloss is 99%,but if I set mtu 9000 the packet loss <1%,
Why did it ? Can I have no packet loss in test? (No reduction in bandwidth )

2.I want to ask about -w option 
256k 4M 2M 64k what does it meam ?
-w =windows size ?
If I use TCP or UDP commands -w is the size of Windows?

Thank you for your help in advance.

**Comment by bmah888** [comment]
The `-w` option sets the size of the socket buffer.  For TCP tests, this also sets the size of the TCP window size.  I guess we should have named the option differently, because it's kind of confusing as-is, but that's what prior tools used (I think).

I'm not sure about the difference in MTU size.  If you run the client with the `--verbose` option, what does it show for the UDP block size and how does that compare with the MTU you set for the interfaces?  In other words this:
```
bmah-centos7:iperf% src/iperf3 --client localhost -p 12345 --udp -w 256k --verbose
iperf 3.7
Linux bmah-centos7.localdomain 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64
Control connection MSS 21845
Setting UDP block size to 21845
```
What's the client output look like?

**Comment by bmah888** [comment]
Closing for lack of additional information.
