### ISSUE TITLE
Iperf throughput in Pbytes/sec

### ISSUE THREAD

**Issue by shashankbr11** [esnet/iperf#922]
On an Intel 82599 adapter iperf is logging the bandwith in Pbytes/sec

My settings are as follows.

- Loopback of the 2 interfaces of the adapter
- Assigning static IPs to each interface
- Configuring one IP as server and other IP as client sends traffic by using -B option for server and connecting to that from the client.

Please sort out this issue as I am expecting something in Gbps

**Comment by bmah888** [comment]
Some operating systems (Linux, in particular, does this) will internally loopback traffic that is sent from one network interface to another on the same host.  It's very likely that in your testing, the packets aren't even going over the Ethernet interface (and loopback), and the Pbps throughput your are seeing is basically the result of testing the software loopback, rather than the network adapter.

I have seen people get the results they wanted in this situation by running the iperf3 server and client in different network namespaces, each one of which could only see one of the network interfaces.  This forces the data to actually egress the machine out one of the network ports, and should give you the answer you're looking for.  (Don't ask me how to do this...I'm more of a BSD person myself, and I'd have to look it up anyway.)

Hope that helps...

**Comment by shashankbr11** [comment]
Thank you @bmah888 for your feedback on this issue.. Your suggestion should give me that expected egress out of a port as I have connected a 10G DA cable between the two ports to sense back the traffic. Could you shed some more clarity on the different network namespaces?

**Comment by bmah888** [comment]
@shashankbr11 : I already wrote above that I really don't know much about this, so much as I'd like, I can't really help you, at least not effectively.  I suggest you start by reading the ip-netns(8) manpage in your favorite Linux distribution...that would probably be my first step.  Good luck!
