### ISSUE TITLE
freebsd 9.2 -s could not work!

### ISSUE THREAD

**Issue by trublemaker** [esnet/iperf#929]
i use iperf3 on  freebsd 9.2 
while run iperf3 -s 
it said "unable to start listener for connections: Protocol not supported"
i debug the code and find while call netannounce(int domain, int proto, char *local, int port)
the param local is null,so it can't work normaly.
so i find the iperf_new_test and set 	test->bind_address = "0.0.0.0" temp
and it can work -s.

**Comment by trublemaker** [comment]
use
 test->bind_address = strdup("0.0.0.0");
and it works ok

**Comment by bmah888** [comment]
Thanks for the report.  You should be aware that FreeBSD 9.2-RELEASE reached end-of-support status with the FreeBSD Project on December 31, 2014 (almost five years ago).  The currently-supported release trains for FreeBSD are 11.x and 12.x.

You didn't say what version of iperf3 you were trying.  When FreeBSD 9 was still supported, we actively did iperf3 development with that version...if there was a problem like this I'm pretty sure we would have found and fixed it.  I just tried the tip of the iperf3 master branch and ran that on a FreeBSD 12.1-RELEASE virtual machine and the server started up fine, accepted client connections, etc.

Since you seem to have a workaround for your particular situation, I'm going to close this bug, unless there's some indication that it affects more current versions. Thanks.
