### ISSUE TITLE
how to arrive the best performance under UDP mode 

### ISSUE THREAD

**Issue by Christinazha** [esnet/iperf#953]
Dear sir,
I use iperf3 to test LAN performance under UDP mode. The commands are as below:
Receiver: Iperf3 –s –p 5200
Sender: Iperf3 –c 192.168.2.1 –p 5200 –P 4(4 is CPU core number) –u –b 10G –l 65507
a. Only add “ –l 65507 “ ,the performance will be arrive at the best. If less than 65507, the results were not as good as set as 65507.
b. for single port test : the single port’s max speed is 10Gbps, the test result was 9.6Gbps.
    if I delete “-l 65507” ,the test results was 8.2Gbps.
Would you please tell me is this right command ,which can set as test standard ? THANKS 

Best regards
Christina

**Comment by bmah888** [comment]
I'm guessing at a few things since there isn't any information about what kind of hardware or operating system you are using (that's why we ask for this information in the issue template).  A few thoughts:

Does the server side report any packet loss?  If so, it's possible that you need to increase the socket buffer sizes (use the `-w` option to the client, experiment with sizes that are at least 128K, or a few multiples of the UDP send size).

The bitrates reported by iperf3 are all with respect to the TCP or UDP payload sizes.  They don't account for packet header overhead, so getting something slightly slower than the line rate is to be expected.  You seem to have gotten approximately 96% of the link bandwidth, which seems fairly reasonable to me.  (Modern computers should be able to saturate a 10Gbps link, definitely a 1Gbps link.)

Have you tried testing with TCP as well to see what kind of throughput you can achieve with that?

**Comment by Christinazha** [comment]
Hi ,sir
Thank you for your reply. I adopt your advice to increasing the socket buffer sizes with “ -w 256K” option to the client, the packet loss would be down.
I still have three questions as below: 
Client :192.168.1.2  ------ > >  Server:192.168.1.1
OS: Centos 7.4
Hardware: CPU : Intel core i5-7500 and NIC with Intel® Ethernet Controller XL710-AM1 as client
                    CPU: Intel Xeon E-2176G and NIC with Intel® Ethernet Controller XL710-AM1 as server
Version of iperf3:3.1.3
Test Results:
TCP mode: I have got approximately 94% of the link bandwidth
Server :
  iperf3 -s
Client:
   iperf3 -c 192.168.1.1 -P 10 -O 5
   [SUM]   0.00-10.00  sec  11.0 GBytes  9.41 Gbits/sec   23             sender
   [SUM]   0.00-10.00  sec  11.0 GBytes  9.44 Gbits/sec                  receiver
UDP mode:
Server: same as TCP
Client:
Situation a：I used default length (8KB for UDP)
  iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5
[SUM]   0.00-10.00  sec  11.2 GBytes  9.58 Gbits/sec  0.055 ms  7996/1462290 (0.55%)

Situation b : I used the largest length 65535-20-8=65507
 iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5 -l 65507
 [SUM]   0.00-10.00  sec  11.2 GBytes  9.62 Gbits/sec  0.328 ms  745/183470 (0.41%)

Situation c : I used “–l 1472” 1472=MTU(1500)-20(IP PACKET HEADER)-8(UDP HEADER)=1472, I think 1472 is the optimal packet size for UDP mode.
  iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5 -l 1472
 [SUM]   0.00-10.00  sec  9.59 GBytes  8.23 Gbits/sec  0.018 ms  14295/6993014 (0.2%)


Situation d : I used “-b 0G ” replace “-b 10G”, the link bandwidth seemed to be increased……
  iperf3 -c 192.168.1.1 -u -b 0G -P 10 -O 5 -l 1472
 [SUM]   0.00-10.00  sec  10.5 GBytes  9.03 Gbits/sec  0.013 ms  16451/7663887 (0.21%)


Question A:
We do not consider the jumbo frame size, the max value of MTU is 1500. 
In theory, I think the optimal packet size should be 1472, then we will have got optimal transmission rate.
Because if the packet size more than 1472, we will face subpackage, which will cause the decrease of transmission rate.
Comparing situation a,b,c. I’d like to know why the larger the packet size, the faster the bandwidth, regardless of the 1500 of MTU?
Packet size(B)	       1472	   8192	65507
Bandwidth(Gbps)	8.23	    9.58	9.62

Question B:
Comparing situation c and situation d , would you please tell me the difference between “-b 0G” and “-b 10G”. In the test,which will be better?
The max bandwidth of NIC’s single port is 10Gbps.

Question C:
In UDP mode, we’ve got a percentage.Could you give a range of percentage for reference, then I can know the lan performance is good or not?
  16451/7663887 (0.21%)

I am looking forward to your reply!
THANKS
Christina

**Comment by Christinazha** [comment]
Hi ,sir
Thank you for your reply. I adopt your advice to increasing the socket buffer sizes with “ -w 256K” option to the client, the packet loss would be down.
I still have three questions as below:
Client :192.168.1.2 ------ > > Server:192.168.1.1
OS: Centos 7.4
Hardware: CPU : Intel core i5-7500 and NIC with Intel® Ethernet Controller XL710-AM1 as client
CPU: Intel Xeon E-2176G and NIC with Intel® Ethernet Controller XL710-AM1 as server
Version of iperf3:3.1.3
------------------------------------------------------------------------------------------------------------------------------
Test Results:
TCP mode: I have got approximately 94% of the link bandwidth
Server :iperf3 -s
Client:
iperf3 -c 192.168.1.1 -P 10 -O 5
[SUM] 0.00-10.00 sec 11.0 GBytes 9.41 Gbits/sec 23 sender
[SUM] 0.00-10.00 sec 11.0 GBytes 9.44 Gbits/sec receiver
-------------------------------------------------------------------------------------------------------------------------------
UDP mode:
Server: same as TCP
Client:
Situation a：I used default length (8KB for UDP)
iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5
[SUM] 0.00-10.00 sec 11.2 GBytes 9.58 Gbits/sec 0.055 ms 7996/1462290 (0.55%)
Situation b : I used the largest length 65535-20-8=65507
iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5 -l 65507
[SUM] 0.00-10.00 sec 11.2 GBytes 9.62 Gbits/sec 0.328 ms 745/183470 (0.41%)
Situation c : I used “–l 1472” 1472=MTU(1500)-20(IP PACKET HEADER)-8(UDP HEADER)=1472, I think 1472 is the optimal packet size for UDP mode.
iperf3 -c 192.168.1.1 -u -b 10G -P 10 -O 5 -l 1472
[SUM] 0.00-10.00 sec 9.59 GBytes 8.23 Gbits/sec 0.018 ms 14295/6993014 (0.2%)
Situation d : I used “-b 0G ” replace “-b 10G”, the link bandwidth seemed to be increased……
iperf3 -c 192.168.1.1 -u -b 0G -P 10 -O 5 -l 1472
[SUM] 0.00-10.00 sec 10.5 GBytes 9.03 Gbits/sec 0.013 ms 16451/7663887 (0.21%)
-------------------------------------------------------------------------------------------------------------------------------
Question A:
We do not consider the jumbo frame size, the max value of MTU is 1500.
In theory, I think the optimal packet size should be 1472, then we will have got optimal transmission rate.
Because if the packet size more than 1472, we will face subpackage, which will cause the decrease of transmission rate.
Comparing situation a,b,c. I’d like to know why the larger the packet size, the faster the bandwidth, regardless of the 1500 of MTU?
Packet size(B)      1472    8192    65507
Bandwidth(Gbps) 8.23      9.58     9.62
Question B:
Comparing situation c and situation d , would you please tell me the difference between “-b 0G” and “-b 10G”. In the test,which will be better?
The max bandwidth of NIC’s single port is 10Gbps.
Question C:
In UDP mode, we’ve got a percentage.Could you give a range of percentage for reference, then I can know the lan performance is good or not?
16451/7663887 (0.21%)
I am looking forward to your reply!
THANKS
Christina


发件人: Bruce A. Mah <notifications@github.com>
发送时间: 2020年4月17日 0:48
收件人: esnet/iperf <iperf@noreply.github.com>
抄送: zha.hui(查慧) <zha.hui@advantech.com.cn>; Author <author@noreply.github.com>
主题: Re: [esnet/iperf] how to arrive the best performance under UDP mode (#953)


I'm guessing at a few things since there isn't any information about what kind of hardware or operating system you are using (that's why we ask for this information in the issue template). A few thoughts:

Does the server side report any packet loss? If so, it's possible that you need to increase the socket buffer sizes (use the -w option to the client, experiment with sizes that are at least 128K, or a few multiples of the UDP send size).

The bitrates reported by iperf3 are all with respect to the TCP or UDP payload sizes. They don't account for packet header overhead, so getting something slightly slower than the line rate is to be expected. You seem to have gotten approximately 96% of the link bandwidth, which seems fairly reasonable to me. (Modern computers should be able to saturate a 10Gbps link, definitely a 1Gbps link.)

Have you tried testing with TCP as well to see what kind of throughput you can achieve with that?

**Comment by bmah888** [comment]
I think there's not really an iperf3 issue here but I'll try to quickly try to answer your outstanding questions:

a) Larger packets often result in a faster throughput because there are some fixed costs (in terms of time) that occur once per packet regardless of how big the packet size is.  Larger packets mean fewer packets for the same throughput, thus less overhead.

b) `-b0` tells the sender to transmit packets as fast as it can.  For UDP, this often results in packets being dropped because the sender can generate packets faster than they can be sent on the network.  `-b10g` tells the sender to limit its speed to 10Gbps.  Note that figure is a rate of UDP payload, but due to packet overheads you won't ever be able to get exactly 10Gbps.

c) That percentage says what fraction of packets didn't make it to the receiver.  My guess is that most of the 0.21% of packets were dropped on the sender or the receiver, not on the LAN itself.

For the answers to other network performance-related questions, you might want to take a look at a Web site my colleagues have put together, https://fasterdata.es.net/ .
