### ISSUE TITLE
Cygwin1.dll update

### ISSUE THREAD

**Issue by dahavey** [esnet/iperf#960]
Hi, I'm Daniel Havey from Microsoft Windows Transport.  There was a bug in the cygwin1.dll that limited the receive buffer size for TCP sends.  This caps the throughput on all tools that use cygwin including iperf.  The details are described in my blogpost: 

https://techcommunity.microsoft.com/t5/networking-blog/windows-network-performance-suffering-from-bad-buffering/ba-p/339668

We worked with RedHat and the bug has been fixed.  Can you please update your cygwin1.dll from the cygwin website?

**Comment by bmah888** [comment]
Hi Daniel, this is Bruce Mah, maintainer of iperf3 at ESnet.  Thanks for your note!  Is this the same issue that we discussed a few years back in #463?  ESnet doesn't provide binaries for Windows or any other platform (partially for this reason).  There are some Cygwin binaries on https://iperf.fr/, but to be frank I wish the maintainer of that Web site would take them down because they're quite old and have known security issues.  It'd be great if they wanted to host up-to-date versions of iperf3 for Windows (or whatever other platform).  I have been trying to contact them for several years, off-and-on, without success.  I'll send another query and try to get their attention.

**Comment by bmah888** [comment]
As indicated in my last comment, this isn't really an ESnet thing...rather a problem for people who are building and packaging iperf3 for Cygwin.  Closing for now...thanks for bring this up!
