### ISSUE TITLE
In TCP mode, how do I count the number of packets delivered？

### ISSUE THREAD

**Issue by zhibindaxia** [esnet/iperf#977]
1. In TCP mode, how do I count the number of packets delivered？

2. In this case, if I wanted to change the size of CWND by writing my own code within 10 seconds of the run, what would I do? Can you do this without modifying the iperf source code?

server: iperf3 -s -p 5001 &
client: ipef3 -c 10.0.0.1 -p 5001 -t 10 -w 200K

**Comment by bmah888** [comment]
1. iperf3 doesn't have a way to count actual TCP packets sent and received (as opposed to send/receive operations within the application).  The only reason this works with UDP is because each send/receive operation maps to exactly one packet on the wire.  If the number of packets is important to you, you could considering using something like tcpdump or Wireshark to capture packets, maybe on the iperf3 client or server host, and filter appropriately to find the TCP packets of interest.

2.  The congestion window size is determined dynamically by TCP at run-time...this is a part of the TCP protocol specifications.  You can set the maximum congestion window size on a per-socket basis...this is what the `-w` command-line flag does.  It sounds like you want to do something like `-w` but have it take effect after 10 seconds?  There's not currently a way to do that within iperf3.

**Comment by zhibindaxia** [comment]
Thank you for your answer.



---Original---
